### ISSUE TITLE
How can I use a proxy server to proxy all Database calls?

### ISSUE THREAD

**Issue by balexandre** [tediousjs/tedious#1011]
Just like in [`mysql2`](https://github.com/sidorares/node-mysql2/blob/master/documentation/Extras.md#connecting-using-custom-stream) database driver, how can we use a proxy server to route calls?

Hosting in a dynamic IP provider (like Heroku) and have an Azure Database (that requires a whitelist IP address) it's almost impossible unless you open all IP range, and that goes against the propose of the firewall ... 

I was wondering if there is a non-documented way to connect to a proxy (or socket proxy)

**Comment by MichaelSun90** [comment]
Hi @balexandre, unfortunately, I do not think there is a way to form a proxy connection using tedious. I try to search around, and I did not find any related modules that can help with this purpose. 😓

**Comment by arthurschreiber** [comment]
In theory that would be possible - we'd just have to allow passing in a custom stream instead of opening up a socket for communication.

**Comment by Instakilla** [comment]
> Теоретически это было бы возможно - нам просто нужно было бы разрешить передачу пользовательского потока вместо открытия сокета для связи.

100%

**Comment by ygoyal25** [comment]
Hi,
Is there any plan to add the custom stream to use a proxy server for connection?

**Comment by Thenkei** [comment]
Same issue here. While trying to use a reverse-proxy and proxy-socks.

```
at Login7TokenHandler.onErrorMessage (/node_modules/tedious/lib/token/handler.js:245:19)
      at Readable.<anonymous> (/node_modules/tedious/lib/token/token-stream-parser.js:26:33)
      at Readable.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at next (node:internal/streams/from:98:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
```

**Comment by martin-d-aleksandrov** [comment]
Hi Folks, 
we are interested in connecting to MSSQL over SOCKS proxy as well. Any way to achieve that? How about using the `custom connector` example - https://github.com/tediousjs/tedious/blob/master/examples/custom-connector.js?

Thanks,
Martin

**Comment by MichaelSun90** [comment]
Hi @martin-d-aleksandrov, I have not worked with SOCKS before. If it returns a Node.js Stream compatible stream, then the custom connector should work for this case. I think the discussion [here](https://github.com/tediousjs/tedious/issues/1572#issuecomment-1751672427) may provide a additional explanation on this.
