### ISSUE TITLE
NTLM: "Login failed for user XXXXXX" but can log in using MSSQL SMC and .Net's SqlClient

### ISSUE THREAD

**Issue by steve-king-ky** [tediousjs/tedious#1076]
Hello everyone.

I'm not sure why this is happening. The following script fails when attempting to use a specific domain account which has access to the database named in the "database" config attribute.

I'm running the script from the command-line which I launched under the same account which needs to access the database.

I can connect using this account's credentials to MSSQL Management Studio (and can access said database) and I can also access it using these credentials using MS SqlClient.

Finally, if I switch the credentials in this script to my own and run the script under my own account, it works as expected.

The only imaginable variable I can think of is that the "real" user name has a space in it (I didn't create it, my central security team did so I have zero control over that). It's something like "XY-SQL-APP RW". I doubt that has anything to do with it but just throwing it out there.

The exact error I'm getting is "ConnectionError: Login failed for user 'DOMAIN\XT-SQL-APP RW'. The full error appears after the code.

I'm bummed because if I can't get this to work I'm going to have to build this application in .Net when the rest of the application is Javascript (Vue.js & Node). This particular application was to be an API.

```
var Connection = require("tedious").Connection;
var Request = require("tedious").Request;
var TYPES = require("tedious").TYPES;

("use strict");

var config = {
  server: "SERVER",
  authentication: {
    type: "ntlm",
    options: {
      domain: "DOMAIN",
      userName: "xxxxxxxx,
      password: "xxxxxxxx",
      intanceName: "INSTANCENAME"
    }
  },
  options: {
    database: "DBNAME",
    trustServerCertificate: true,
    encrypt: true
  }
};

var cn = new Connection(config);

console.log(cn.config.authentication.options);

cn.on("connect", err => {
  if (err) {
    console.log(err);
  } else {
    console.log("CONNECTED");    
  }
});

```
Full error message:
```
{ ConnectionError: Login failed for user 'PERS\ST-SQL-B50 RW'.
    at ConnectionError (c:\Projects\apis\b50api\node_modules\tedious\lib\errors.js:13:12)
    at Parser.tokenStreamParser.on.token (c:\Projects\apis\b50api\node_modules\tedious\lib\connection.js:853:51)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.parser.on.token (c:\Projects\apis\b50api\node_modules\tedious\lib\token\token-stream-parser.js:37:14)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (c:\Projects\apis\b50api\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (c:\Projects\apis\b50api\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Parser.Readable.push (c:\Projects\apis\b50api\node_modules\readable-stream\lib\_stream_readable.js:241:10)
  message: 'Login failed for user \'PERS\\ST-SQL-B50 RW\'.',
  code: 'ELOGIN' }
```

**Comment by IanChokS** [comment]
Hi @steve-king-ky, what port is your server listening on? Tedious defaults to port 1433.

**Comment by steve-king-ky** [comment]
Yes, it's listening on 1433.

**Comment by IanChokS** [comment]
(I'm not sure if this is relevant, but just an fyi you posted different usernames: `XY-SQL-APP RW` and `XT-SQL-APP RW`)

**Comment by steve-king-ky** [comment]
My bad. That was just a typo on my part.

**Comment by IanChokS** [comment]
What version of tedious and mssql server are you using?

**Comment by steve-king-ky** [comment]
tedious: 8.2.0
mssql: 6.2.0

**Comment by steve-king-ky** [comment]
By the way, I downloaded *msnodsqlv8" and was able to connect using that library.

**Comment by IanChokS** [comment]
Hmmm... Can you try your script again but capturing the [`debug`, `infoMessage` and `errorMessage`](https://tediousjs.github.io/tedious/api-connection.html#event_infoMessage) events from connection?

E.g., 
```js
connection.on('debug', function(info) {...});
connection.on('errorMessage', function(info) {...});
connection.on('infoMessage', function(info) {...});
``` 

Also just to clarify, are you saying that the username/password you're attempting to use with Tedious is not working, but the same username works in powershell and SQL Server Management Studio?

**Comment by steve-king-ky** [comment]
Here is the output:

```
{
  userName: 'XT-SQL-XXX XX',
  password: 'XXXXX',
  domain: 'XXXX'
}
DEBUG connected to XXXX560:1433
DEBUG State change: Connecting -> SentPrelogin
DEBUG State change: SentPrelogin -> SentTLSSSLNegotiation
DEBUG TLS negotiated (ECDHE-RSA-AES256-SHA384, TLSv1.2)
DEBUG State change: SentTLSSSLNegotiation -> SentLogin7WithNTLMLogin
ERROR ErrorMessageToken {
  name: 'ERROR',
  event: 'errorMessage',
  number: 18456,
  state: 1,
  class: 14,
  message: "Login failed for user 'XXXX\\XT-SQL-XXX XX'.",
  serverName: 'XXXX560',
  procName: '',
  lineNumber: 1
}
ConnectionError: Login failed for user 'XXXX\XT-SQL-XXX XW'.
    at ConnectionError (c:\Projects\apis\b50api\node_modules\tedious\lib\errors.js:13:12)
    at Parser.<anonymous> (c:\Projects\apis\b50api\node_modules\tedious\lib\connection.js:853:51)
    at Parser.emit (events.js:311:20)
    at Parser.<anonymous> (c:\Projects\apis\b50api\node_modules\tedious\lib\token\token-stream-parser.js:37:14)
    at Parser.emit (events.js:311:20)
    at addChunk (c:\Projects\apis\b50api\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (c:\Projects\apis\b50api\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Parser.Readable.push (c:\Projects\apis\b50api\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at Parser.Transform.push (c:\Projects\apis\b50api\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at doneParsing (c:\Projects\apis\b50api\node_modules\tedious\lib\token\stream-parser.js:122:14) {
  message: "Login failed for user 'XXXX\\XT-SQL-XXX XX'.",
  code: 'ELOGIN'
}
DEBUG State change: SentLogin7WithNTLMLogin -> Final
DEBUG connection to XXXX560:1433 closed
DEBUG State is already Final
```

**Comment by IanChokS** [comment]
Hi @steve-king-ky 

Unfortunately I wasn't able to reproduce your error. I've tested `ntlm` login with a username
```
test-user A
```
 and I was able to log in. I'm not sure what is causing your issue, but from the looks of the debug log, tedious is talking with the server just fine. 

To be honest, I'm not sure why you're not able to login 🤔

**Comment by ybrodsky** [comment]
I have exactly the same problem.
Same as @steve-king-ky I was able to connect with msnodesqlv8

**Comment by IanChokS** [comment]
Hi @ybrodsky what was your set up?

**Comment by ybrodsky** [comment]
Never mind, I am an idiot.

Sorry.

**Comment by IanChokS** [comment]
@ybrodsky what was wrong and what did you fix? Any insight can be helpful 😄

**Comment by ybrodsky** [comment]
I followed the steps in this answer https://stackoverflow.com/a/12774856/1655756 and it solved my issue.

**Comment by IanChokS** [comment]
Hmm, I wonder why you were able to connect with **msnodesqlv8** before though? 🤔

**Comment by ybrodsky** [comment]
I think I wasnt being able to connect wth msnodesqlv8 either, but it was masking the error and not showing it until when I tried to run a query.
First time dealing with mssql so... lots of begginers mistakes 😢
