### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by uclnj** [tediousjs/tedious#1087]
tedious@8.3.0
node@10.16.3

I have a small startup module in node that connects up to MSSQL, pulls down the daily region codes and caches them.  In testing, we cut connectivity to MSSQL and fired up node.  After adding a try...catch to damn near every method I could find, Node still crashes out with the following snippet.

```
try {
            connection.on("connect", function (err) {
                if (err) {
                    console.log(`startup[81]::tedious > connect ${err}`)
                } else { connection.execSql(request) }
            }).connect()
        } catch (err) {
            console.log(err)
        }
```

The if(err) catches and shows the error message but then an exception is thrown which is not caught by code.  **Where do I catch this**?

```
Server listening on port 4000
startup[81]::tedious > connect ConnectionError: Failed to connect to xxx.yyy.local:1433 in 5000ms

events.js:174
      throw er; // Unhandled 'error' event
      ^
ConnectionError: Connection lost - Could not connect (sequence)
    at ConnectionError (C:\code\xxxnode\node_modules\tedious\lib\errors.js:13:12)
    at Connection.socketError (C:\code\xxxnode\node_modules\tedious\lib\connection.js:1312:54)
    at _connector.Connector.execute (C:\code\xxxnode\node_modules\tedious\lib\connection.js:1134:21)
    at SequentialConnectionStrategy.connect (C:\code\xxxnode\node_modules\tedious\lib\connector.js:87:14)
    at Socket.onError (C:\code\xxxnode\node_modules\tedious\lib\connector.js:100:12)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Connection.socketError (C:\code\xxxnode\node_modules\tedious\lib\connection.js:1312:12)
    at _connector.Connector.execute (C:\code\xxxnode\node_modules\tedious\lib\connection.js:1134:21)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by MichaelSun90** [comment]
Hi @uclnj, you could try to add a handler like this:
```nodejs
connection.on('error', function(err) {
  console.log(err);
}
```
Add this after you "connection.on" handler. This should catch the error. 
You can also check our document page for this and other supported events and APIs.
http://tediousjs.github.io/tedious/api-connection.html#event_error
