### ISSUE TITLE
ConnectionError [SequelizeConnectionError]: this.lib.Connection is not a constructor

### ISSUE THREAD

**Issue by CamelJohn** [tediousjs/tedious#1092]
Hi all,

I've deployed my nodejs backend to Azure - and am trying to connect to SQL SERVER (2000) also on Azure and I get an error. localy this worked fine.

```
const sequelize = new Sequelize(
  process.env.DATABASE,
  process.env.DATABASE_USER,
  process.env.DATABASE_PASSWORD,
  {
    host: process.env.DATABASE_HOST,
    dialect: 'mssql',
    dialectModule: 'tedious',
    dialectOptions: {
      // options: {
        encrypt: true,
        useUTC: false,
        dateFirst: 1,
        trustServerCertificate: true,
        enableArithAbort: false,
      // },
    },
  }
);
```

On my local machine all works fine.

but when i deployed my app this is what i get: 

```
ConnectionError [SequelizeConnectionError]: this.lib.Connection is not a constructor
    at D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:114:15
    at tryCatcher (D:\home\site\wwwroot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21) {
  name: 'SequelizeConnectionError',
  parent: TypeError: this.lib.Connection is not a constructor
      at D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:63:26
      at Promise._execute (D:\home\site\wwwroot\node_modules\bluebird\js\release\debuggability.js:384:9)
      at Promise._resolveFromExecutor (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:518:18)
      at new Promise (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:103:10)
      at ConnectionManager.connect (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:62:12)
      at D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:311:50
      at tryCatcher (D:\home\site\wwwroot\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:439:21),
  original: TypeError: this.lib.Connection is not a constructor
      at D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:63:26
      at Promise._execute (D:\home\site\wwwroot\node_modules\bluebird\js\release\debuggability.js:384:9)
      at Promise._resolveFromExecutor (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:518:18)
      at new Promise (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:103:10)
      at ConnectionManager.connect (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:62:12)
      at D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:311:50
      at tryCatcher (D:\home\site\wwwroot\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\home\site\wwwroot\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (D:\home\site\wwwroot\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
}
```

was wondering if anyone had the same issue :)

**Comment by MichaelSun90** [comment]
Hi @CamelJohn, from the log that you provide, it seems this error is thrown from mssql\connection-manager.js. Have you tried to raise a question on their side yet?

**Comment by CamelJohn** [comment]
Hi @MichaelSun90 , truth is, since i'm relatively new to programming, i had no clue it had to do with mssql - thanks, i'm opening an issue as we speak :)

**Comment by CamelJohn** [comment]
I found the culprit - I'm embarrased to say it was not a tedious/sequelize error.
the cloud witch we've been using is Azure and our app was deployed via IIS - witch does not communicate well with my dependancies. we switched to a linux server and all is well.
