### ISSUE TITLE
Remove dependency on ps

### ISSUE THREAD

**Issue by bestickley** [tediousjs/tedious#1125]
I'm using a hardened image of Node.js based on RHEL that doesn't have the command "ps" available. Therefore, when I run my Nest.js app I get this output:
```
[2:56:09 PM] Found 0 errors. Watching for file changes.

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 1890 ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bridge-server@0.5.0 start:debug: `rimraf dist && nest start --debug --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bridge-server@0.5.0 start:debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-07-09T14_56_09_384Z-debug.log
[node@f9318fd5d443 app]$ [Nest] 1890   - 07/09/2020, 2:56:20 PM   [NestFactory] Starting Nest application...
[Nest] 1890   - 07/09/2020, 2:56:22 PM   [NestApplication] Nest application successfully started
```
The application runs fine but the error message is annoying. Could this dependency be removed?

Note: if I run `yum install procps` the error message is removed but due to security reasons, I don't want to install it.

Thank you!

**Comment by bestickley** [comment]
Resolved.
