### ISSUE TITLE
Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by peem420** [tediousjs/tedious#1130]
25 Jul 21:51:29 - [error] [MSSQL:fb83a45d.a4a908] Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed
25 Jul 22:22:12 - [info] [MSSQL-CN:Dev] Error connecting to server : localhost, database : Dev, port : 1433, user : NodeRed
ConnectionError: Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed
at Connection. (C:\Users\greed.node-red\node_modules\mssql\lib\tedious\connection-pool.js:68:17)
at Object.onceWrapper (events.js:422:26)
at Connection.emit (events.js:315:20)
at Connection.socketError (C:\Users\greed.node-red\node_modules\tedious\lib\connection.js:1290:12)
at Socket. (C:\Users\greed.node-red\node_modules\tedious\lib\connection.js:1125:14)
at Socket.emit (events.js:327:22)
at errorOrDestroy (internal/streams/destroy.js:108:12)
at onwriteError (_stream_writable.js:418:5)
at onwrite (_stream_writable.js:445:5)
at doWrite (_stream_writable.js:399:11) {
code: 'ESOCKET',
originalError: ConnectionError: Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed
at ConnectionError (C:\Users\greed.node-red\node_modules\tedious\lib\errors.js:13:12)
at Connection.socketError (C:\Users\greed.node-red\node_modules\tedious\lib\connection.js:1290:56)
at Socket. (C:\Users\greed.node-red\node_modules\tedious\lib\connection.js:1125:14)
at Socket.emit (events.js:327:22)
at errorOrDestroy (internal/streams/destroy.js:108:12)
at onwriteError (_stream_writable.js:418:5)
at onwrite (_stream_writable.js:445:5)
at doWrite (_stream_writable.js:399:11)
at writeOrBuffer (_stream_writable.js:387:5)
at Socket.Writable.write (_stream_writable.js:318:11) {
code: 'ESOCKET'
}
}

{"code":"ESOCKET",
"message":"Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed",
"details":"Failed to connect to localhost:1433 - Cannot call write after a stream was destroyed",
"name":"ConnectionError"}

**Comment by IanChokS** [comment]
Hi @peem420 sorry for not replying sooner. What is your config look like? Connecting to sql server for the first time might also require some sql server set up (see [tips here](https://tediousjs.github.io/tedious/frequently-encountered-problems.html))

**Comment by Hamza-Aziz** [comment]
Hi
try this script
const Sequelize = require("sequelize");
const sequelize = new Sequelize("context", "sa", "youPass", {
  host: "localhost",
  dialect: "mssql",
  dialectOptions: {
    options: {
      nstanceName: "SQLEXPRESS",
      encrypt: false,
    },
  },
});

sequelize
  .authenticate()
  .then(() => {
    console.log("Connection has been established successfully.");
  })
  .catch((err) => {
    console.error("Unable to connect to the database:", err);
  });
