### ISSUE TITLE
ConnectionError: Failed to connect to host:1433 - Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by CesarAMM** [tediousjs/tedious#1160]
Tengo tedious v:6.10.2 y sql server 2008

```js
const config = {
    server: 'host',
    authentication:{
        type:'default',
        options:{
            userName: 'usuario',
            password: 'pass',
            database: 'name_base'
        }
    },
    pool:{
        max: 230,
        min: 0,
        idleTimeoutMillis: 30000,
        destroyed: false
    },
    options:{
        port:4133,
        tdsVersion: '7_1'
    }
};

(node:11384) UnhandledPromiseRejectionWarning: ConnectionError: Failed to connect to host:1433 - Cannot call write after a stream was destroyed
    at Connection.<anonymous> (C:\Users\cesar.monroy\Documents\Desarrollos\Unisuper\Unisuper_Sac\node_modules\mssql\lib\tedious\connection-pool.js:68:17)
    at Object.onceWrapper (events.js:291:20)
    at Connection.emit (events.js:203:13)
    at Connection.socketError (C:\Users\node_modules\mssql\node_modules\tedious\lib\connection.js:1290:12)
    at Socket.<anonymous> (C:\Users\node_modules\mssql\node_modules\tedious\lib\connection.js:1125:14)
    at Socket.emit (events.js:208:15)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:433:5)
    at onwrite (_stream_writable.js:460:5)
    at doWrite (_stream_writable.js:414:11)
(node:11384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Alguien me podria apoyar :)

**Comment by CesarAMM** [comment]
Perdón es sql 2012

**Comment by IanChokS** [comment]
Hi @CesarAMM, see if any of the[ following hints](https://tediousjs.github.io/tedious/frequently-encountered-problems.html) might help. There could be many reasons why you cannot connect. I might also suggest raising an issue on [node-mssql ](https://github.com/tediousjs/node-mssql) as well.

**Comment by CesarAMM** [comment]
Gracias, encontré el problema

Fue en el fireware con las Reglas de entrada y salida.
