### ISSUE TITLE
Error: No event 'socketConnect' in state 'SentPrelogin'

### ISSUE THREAD

**Issue by vishvajitgirase** [tediousjs/tedious#1234]
I am trying to connect mssql database with node.js using knex but i am facing issue
Error: No event 'socketConnect' in state 'SentPrelogin'
    at Connection.dispatchEvent (C:\Users\temp\Documents\PRactice\node_modules\tedious\lib\connection.js:1281:26)
    at Connection.socketConnect (C:\Users\temp\Documents\PRactice\node_modules\tedious\lib\connection.js:1303:10)
    at C:\Users\temp\Documents\PRactice\node_modules\tedious\lib\connection.js:1145:12
    at Socket.onConnect (C:\Users\temp\Documents\PRactice\node_modules\tedious\lib\connector.js:106:7)
    at Socket.emit (events.js:314:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1131:10)
Emitted 'error' event on Connection instance at:
    at Connection.dispatchEvent (C:\Users\temp\Documents\PRactice\node_modules\tedious\lib\connection.js:1281:12)
    at Connection.socketConnect (C:\Users\temp\Documents\PRactice\node_modules\tedious\lib\connection.js:1303:10)
    [... lines matching original stack trace ...]
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1131:10)
[nodemon] app crashed - waiting for file changes before starting...

my code is 
var knex = require('knex')({  
  client: 'mssql',
  version:"7_1",  
   connection: {  
    user: 'sa',  
    password: 'Admin@123',  
    server: 'localhost',  
    database: 'Demo'  
   }  
 });  

 knex.select("*").from("Country")  
 .then(function (depts){  
   depts.forEach((dept)=>{ //use of Arrow Function  
     console.log({...dept});  
   });  
 }).catch(function(err) {  
 // All the error can be checked in this piece of code  
   console.log(err);  
 }).finally(function() {  
   // To close the connection pool  
   knex.destroy();  
 });

**Comment by arthurschreiber** [comment]
Which version of `tedious` are you using via `knex`? You should be able to see the exact version via the `package-lock.json` file.

**Comment by vishvajitgirase** [comment]
tedious version : - 6.7.0

**Comment by jeremy-w** [comment]
this same issue bit me on upgrade. (https://github.com/knex/knex/issues/4337#issuecomment-791034995) try nuking node_modules and reinstalling.

the tedious version you have installed predates the switch to requiring explicit connect(), while knex expects the latter. (and knex requires a version of tedious that agrees with it in its peer dep version spec, and yet somehow we both wound up with outdated tedious modules - go figure.)

NOTE: This bug was duped as https://github.com/knex/knex/issues/4353

**Comment by vishvajitgirase** [comment]
It worked thank you for help.
