### ISSUE TITLE
Node 16 getting error  "class HttpsProxyAgent extends agent_base_1.Agent"  TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Vic-tator** [tediousjs/tedious#1372]
Hey,
recently moved to node 16 getting the following message:

/usr/src/app/node_modules/@azure/core-rest-pipeline/node_modules/https-proxy-agent/dist/agent.js:37
class HttpsProxyAgent extends agent_base_1.Agent {
                                           ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/src/app/node_modules/@azure/core-rest-pipeline/node_modules/https-proxy-agent/dist/agent.js:37:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@azure/core-rest-pipeline/node_modules/https-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@azure/core-rest-pipeline/dist/index.js:11:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

**Comment by MichaelSun90** [comment]
Hi @Vic-tator, not sure how this issue is related to tedious? From you the error log, I did not see any entry is specifically related to tedious. Can you provide a bit more detail on how to reproduce this with tedious?

**Comment by Vic-tator** [comment]
Hey, @MichaelSun90  from what i looked in my project tedious is the only package that using @azure/core-rest-pipeline.
tedious dependencies include:
"@azure/identity": "^1.5.2"
@azure/identity dependencies:
"@azure/core-rest-pipeline": "^1.1.0"

When i am trying to create a new connection : 

const { Connection, Request } = require('tedious')
.
.
.
connection = new Connection(connectionOptions)

I am getting the error above.
The only thing that changed is that we moved our project to use node 16 instead of node 14.
Until then everything worked with no issue.
Thanks in advance :)

**Comment by Vic-tator** [comment]
Hey, tried to do simple connection (example from Microsoft site) using tedious got the same error:

const Connection = require('tedious').Connection
const config = {
  server: 'XXXX', // update me
  authentication: {
    type: 'default',
    options: {
      userName: 'user', // update me
      password: 'password' // update me
    }
  },
  options: {
    // If you are on Microsoft Azure, you need encryption:
    encrypt: true,
    database: 'db' // update me
  }
}
const connection = new Connection(config)
connection.on('connect', err => {
  if (err) {
    console.log('err', err)
  } else {
    console.log('Connected')
  }
})

connection.connect()

error:

/node_modules/@azure/core-rest-pipeline/node_modules/https-proxy-agent/dist/agent.js:37
class HttpsProxyAgent extends agent_base_1.Agent {
                                           ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/node_modules/@azure/core-rest-pipeline/node_modules/https-proxy-agent/dist/agent.js:37:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/node_modules/@azure/core-rest-pipeline/node_modules/https-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by MichaelSun90** [comment]
Hi @Vic-tator, I just did a quick test, and the result is kind of a bit strange. I was on NodeJS 14, so I use the windows installer for NodeJS version 16.13.0 from their website to update the NodeJS to Node16. Then I can run a simple connection test with tedious without a problem. Then I want to double-check my tedious version with npm, and all my npm-related commands were returning me the error: "TypeError: Class extends value undefined is not a constructor or null". Then I use nvm to change my Node version back to 14, and npm behaves normally again. Then I use nvm to upgrade Node 14 to Node 16, and everything still works. Npm works fine. I run a connection test, and no error is reported.  
May I ask which way did you use to upgrade your Node version? If you have not tried to use nvm, can you give it a try, see what behavior you get on your side?
