### ISSUE TITLE
not able to connect to Microsoft Fabric

### ISSUE THREAD

**Issue by tchenazure** [tediousjs/tedious#1563]
**Software versions**
* Tedious: 16.2.0
* SQL Server: Microsoft Fabric(12.0.2000.8)
* Node.js:18.17.0

**Additional Libraries Used and Versions**

node-mssql: 9.1.1

**Table schema**

**Connection configuration**
`
const sqlConfig = {
  database: 'Root Data Warehouse',
  server: 'gextrl4zm6culiitwxjyp6ss5y-vh3r3oacuziunk6ffxzgvl2tay.datawarehouse.pbidedicated.windows.net',
  port: 1433,
  pool: {
    max: 10,
    min: 0,
    idleTimeoutMillis: 30000
  },
  options: {
    encrypt: true, // for azure
    trustServerCertificate: true// change to true for local dev / self-signed certs
  },
  authentication: {
    type: 'azure-active-directory-service-principal-secret',
    options: {
      clientId: '74329c3d-6630-40f2-bbb6-ecb70659f0b2',
      clientSecret: 'G8RH1K.=G-HHwG8R8=qts2]7N0JYy8hp',
      tenantId: 'af382f31-6799-4585-a113-b5d387fa52ee'
    }
  },
};
`

**Problem description**

Got an error message when connecting to Microsoft Fabric 
Uncaught ConnectionError Error: Connection lost - read ECONNRESET

**Expected behavior**

Microsoft Fabric should be connected by service principal, query should work after the connection is established.

**Actual behavior**

It doesn't connect at all.

**Error message/stack trace**

Uncaught ConnectionError Error: Connection lost - read ECONNRESET
    at socketError (c:\test\fabric\node_modules\tedious\lib\connection.js:1410:26)
    at <anonymous> (c:\test\fabric\node_modules\tedious\lib\connection.js:1160:16)
    at emit (events:526:35)
    at emitErrorNT (internal/streams/destroy:151:8)
    at emitErrorCloseNT (internal/streams/destroy:116:3)
    at processTicksAndRejections (internal/process/task_queues:82:21)
    --- TickObject ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at emitInitScript (internal/async_hooks:504:3)
    at nextTick (internal/process/task_queues:132:5)
    at onDestroy (internal/streams/destroy:103:15)
    at Socket._destroy (net:812:5)
    at _destroy (internal/streams/destroy:109:10)
    at destroy (internal/streams/destroy:71:5)
    at onStreamRead (internal/stream_base_commons:217:12)
    at callbackTrampoline (internal/async_hooks:130:17)
    --- TCPWRAP ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at Socket.connect (net:1176:7)
    at connect (net:244:17)
    at <anonymous> (c:\test\fabric\node_modules\tedious\lib\connector.js:102:37)
    at connectInSequence (c:\test\fabric\node_modules\tedious\lib\connector.js:101:20)
    --- await ---
    at connectOnPort (c:\test\fabric\node_modules\tedious\lib\connection.js:1157:5)
    at initialiseConnection (c:\test\fabric\node_modules\tedious\lib\connection.js:1072:19)
    at enter (c:\test\fabric\node_modules\tedious\lib\connection.js:2364:12)
    at transitionTo (c:\test\fabric\node_modules\tedious\lib\connection.js:1365:24)
    at reconnect (c:\test\fabric\node_modules\tedious\lib\connection.js:2468:14)
    at dispatchEvent (c:\test\fabric\node_modules\tedious\lib\connection.js:1391:15)
    at socketClose (c:\test\fabric\node_modules\tedious\lib\connection.js:1439:12)
    at <anonymous> (c:\test\fabric\node_modules\tedious\lib\connection.js:1163:16)
    at emit (events:526:35)
    at <anonymous> (net:323:12)
    at callbackTrampoline (internal/async_hooks:130:17)
    --- TCPWRAP ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at Socket.connect (net:1176:7)
    at connect (net:244:17)
    at <anonymous> (c:\test\fabric\node_modules\tedious\lib\connector.js:102:37)
    at connectInSequence (c:\test\fabric\node_modules\tedious\lib\connector.js:101:20)
    --- await ---
    at connectOnPort (c:\test\fabric\node_modules\tedious\lib\connection.js:1157:5)
    at initialiseConnection (c:\test\fabric\node_modules\tedious\lib\connection.js:1072:19)
    at enter (c:\test\fabric\node_modules\tedious\lib\connection.js:2364:12)
    at transitionTo (c:\test\fabric\node_modules\tedious\lib\connection.js:1365:24)
    at connect (c:\test\fabric\node_modules\tedious\lib\connection.js:1035:10)
    at <anonymous> (c:\test\fabric\ted.js:30:12)
    at Module._compile (internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (internal/modules/cjs/loader:1310:10)
    at Module.load (internal/modules/cjs/loader:1119:32)
    at Module._load (internal/modules/cjs/loader:960:12)
    at executeUserEntryPoint (internal/modules/run_main:81:12)
    at <anonymous> (internal/main/run_main_module:23:47)
**Any other details that can be helpful**

**Comment by MichaelSun90** [comment]
Hi @tchenazure, on thing that I noticed is you may have posted your connection credential in the description. If it is for sandbox, then it should be fine. 
In terms for you connection error, under your script, have you try to caught the error and output it? it may review more detail relate to the error. Not sure whether node-mssql will make things differently, but for tedious on its own, you can do it like this by add a console.log in the connect call back:
```js
connection.connect((err) => {
  if (err) {
    console.log(err);
  }
});
connection.
```
also, the error returned maybe a  aggregate, and you can output it as mentioned [here](http://tediousjs.github.io/tedious/api-connection.html) under section : connection.connect(callback).

can you give this a try see if you can get a bit more detail on the error, so we can work from there.

**Comment by tchenazure** [comment]
Hi @MichaelSun90 ,

I got this error:
ConnectionError: Connection lost - read ECONNRESET
    at Connection.socketError (C:\test\FabricConnectionTest\node_modules\tedious\lib\connection.js:1410:26)
    at Socket.<anonymous> (C:\test\FabricConnectionTest\node_modules\tedious\lib\connection.js:1160:16)
    at Socket.emit (node:events:526:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ESOCKET',
  isTransient: undefined
}

**Comment by MichaelSun90** [comment]
Hi @tchenazure, have you tried  the aggregate error option that I mentioned in the pervious message? if that does not return any additional errors underneath that, then you can enable our debug options on tedious side, so it can log more details on the error. 

Here is an example for enable debugging from tedious side:
```js
var config = {
  ...
  options: {
    ...
    // Add this to your configuration file. You can pick and choose which ones to enable. 
    debug: {
      packet: true,
      data: true,
      payload: true,
      token: true
    }
  },
  ...
};
```
Then add this event listener to output the debug messages:
```js
  connection.on('debug', (msg) => {
    console.log(msg);
  });
 ```
 Then can you share the log here, so we can have a bit more information to work with. Thanks!

**Comment by SwadX** [comment]
I am facing a similar issue with connection to Microsoft fabric.
Here is my package version details :
```
  "dependencies": {
    "@azure/identity": "4.0.1",
    "mssql": "10.0.2",
    "tedious": "16.7.0"
  }
```
My node version is : v18.16.0

My code : 

```
const sqlTds = require('tedious');

const azureIdentity = require('@azure/identity');

const tenantId = process.env.TENANT_ID;
const clientId = process.env.CLIENT_ID;
const clientSecret = process.env.CLIENT_SECRET;
const dbServer = "<myfabricwarehouse>.datawarehouse.pbidedicated.windows.net";
const database = "<mydatabase>"

async function demo(){
    config = {
        server: dbServer,
        authentication: {
            type: "azure-active-directory-service-principal-secret",
            options: {
                clientId: clientId,
                clientSecret: clientSecret,
                tenantId: tenantId,
            }
        },
        options: {
            database: database,
            port: 1433,
            debug: {
                packet: true,
                data: true,
                payload: true,
                token: true
              }
        }
    };
    const conn = new sqlTds.Connection(config);
    conn.on('debug',(msg) => {console.log(msg);});
    //conn.on("secure",(clearText) => {console.log(clearText)});
    conn.on('error',(err) => {console.log(err)});
    conn.on('connect',(err) => {
        if (err) {
            console.log('Connection Failure...');
            throw err;
        }
    });

    conn.connect();

}
```
The error I am getting : 

Connection lost - socket hang up
ConnectionError: Connection lost - socket hang up
 at Connection.socketError
            ... node_modules\tedious\lib\connection.js:1344:26)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ESOCKET'
}
State change: SentLogin7Withfedauth -> Final
Connection lost - unexpected end of message stream
ConnectionError: Connection lost - unexpected end of message stream

**Comment by SwadX** [comment]
some more debug messages :
```
State change: Initialized -> Connecting
connected to xxxx.datawarehouse.pbidedicated.windows.net:1433
  PreLogin - version:16.7.0.0, encryption:0x01(ON), instopt:0x00, threadId:0x00000000, mars:0x00(OFF)
State change: Connecting -> SentPrelogin
. . .
State change: SentPrelogin -> SentTLSSSLNegotiation

Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x0161, spid:0x0000, packetId:0x01, window:0x00
. . .
Received
  type:0x12(PRELOGIN), status:0x00(), length:0x1000, spid:0x0000, packetId:0x01, window:0x00
. .  .
Received
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x006B, spid:0x0000, packetId:0x02, window:0x00
. . .
Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x00A6, spid:0x0000, packetId:0x01, window:0x00
. . .
Received
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x003B, spid:0x0000, packetId:0x01, window:0x00
. . .
TLS negotiated (ECDHE-RSA-AES256-GCM-SHA384, TLSv1.2)
  Login7 - TDS:0x74000004, PacketSize:0x00001000, ClientProgVer:0x00000000, ClientPID:0x000079F4, ConnectionID:0x00000000
. . .
 Flags1:0xF0, Flags2:0x00, TypeFlags:0x00, Flags3:0x18, ClientTimezone:-330, ClientLCID:0x00000409
           Hostname:'xxxx', Username:'undefined', Password:'undefined', AppName:'Tedious', ServerName:'xxxx.datawarehouse.pbidedicated.windows.net', LibraryName:'Tedious'
           Language:'us_english', Database:'xxxx', SSPI:'undefined', AttachDbFile:'undefined', 
ChangePassword:'undefined'
State change: SentTLSSSLNegotiation -> SentLogin7Withfedauth

Sent
  type:0x10(LOGIN7), status:0x01(EOM), length:0x019A, spid:0x0000, packetId:0x01, window:0x00
. . .
socket ended
Connection lost - socket hang up
ConnectionError: Connection lost - socket hang up
    at Connection.socketError
```

**Comment by MichaelSun90** [comment]
Hi @SwadX, Thanks for the detail log. Will look into this a bit more, see if we can figure out why it behave like this.

**Comment by SanderBlom** [comment]
Is there any progress on this? I face the same issue both using `service-principal-secret` and token

**Comment by MichaelSun90** [comment]
Hi @SanderBlom, we did some investigation and unfortunately that tedious does not currently support connection to Microsoft Fabric DW. Microsoft Fabric DW has a bit more restricted way for handling incoming connection compare to how tedious currently handles it internally. The team will have a discussion and see when we will have the bandwidth to get this working.

**Comment by elliot-huffman** [comment]
From the authentication side of things, the new PR at #1624 should add authentication support as you can roll any authentication you need from the MSFT side of things.
You can configure your credential chain using the MSFT docs for Fabric to authenticate.

Protocol support is a different thing...

**Comment by aljaz-erzin** [comment]
Ji @MichaelSun90, I am just wondering if you have discussed when (or if) this issue will be addressed? My team is currently in the process of adding Fabric DWH to our nodejs application. We are kind of under pressure by our customers and we need to establish a timeline for this added feature. 
We are facing similar issue (SOCKET HANG UP).

**Comment by David-Engel** [comment]
It's on the team's radar to consider looking at during the next 6 months, but there is no timeline to share at this time.

**Comment by haggholm** [comment]
> It's on the team's radar to consider looking at during the next 6 months, but there is no timeline to share at this time.

Halfway through those next 6 months, are there any updates on timelines?

**Comment by asnnng** [comment]
I would really appreciate if we could get an answer when this could be completed. Without any update and the upcoming deadline of our MS Fabric project we are forced to look at a different solution.

**Comment by pdmangel2** [comment]
This would also help our team to make progress in migrating all our reporting capabilities to Fabric.
Thanks in advance for a quick update on this issue !

**Comment by David-Engel** [comment]
Unfortunately, there is still no timeline from my team as far as contributing this work. I'll bubble it up to some others in case there is someone else who can contribute this.

**Comment by TPVallancourt** [comment]
> Hi @SanderBlom, we did some investigation and unfortunately that tedious does not currently support connection to Microsoft Fabric DW. Microsoft Fabric DW has a bit more restricted way for handling incoming connection compare to how tedious currently handles it internally. The team will have a discussion and see when we will have the bandwidth to get this working.

@MichaelSun90 Would you be able to share details about the difference between how Fabric DW handles incoming connections and what tedious currently does? Using tedious would be the preferred solution for integrating Fabric into our nodejs application, so we would be interested in contributing the fix if it seems feasible.

**Comment by TPVallancourt** [comment]
I was able to connect to Fabric locally using [these changes](https://github.com/tediousjs/tedious/pull/1668). Would appreciate an owner of the repo taking a look - thanks!

**Comment by pdmangel2** [comment]
I also tested locally and can confirm that this solves the issue in this use case.

**Comment by SergGrishkov** [comment]
Hello everyone.
I also faced this problem last week. I suffered, but still I did it, I connected to Fabric DB :)
Example code in my repository: [Connect_to_FabricDB](https://github.com/SergGrishkov/Connect_to_FabricDB) 
My [LinkedIn](www.linkedin.com/in/sergey-grishkov-955511153)

**Comment by AlejandroFerrera** [comment]
Hello @TPVallancourt,

I was using your fix, and it was working perfectly. However, today it started throwing the socket hang up error again. I suspect it might be related to Microsoft Fabric. Have you experienced this issue as well?

@pdmangel2, have you encountered this too?

**Comment by pdmangel** [comment]
Indeed, I did a quick test and got a ESOCKET ConnectionError

**Comment by TPVallancourt** [comment]
Just tested it today and it looks like it no longer works - I would guess it's likely due to the new [TDS version from 11/19](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/b46a581a-39de-4745-b076-ec4dbb7d13ec#published-version). Will take a look at this week and try to get to the bottom of what broke.

**Comment by TPVallancourt** [comment]
Pushed a [change](https://github.com/tediousjs/tedious/pull/1668/commits/a951cb537f9e29dd97e16e11911e2c2bb654729d) that adds a randomly generated TraceID to the prelogin payload and got the connection working on my machine. Still need to clean up the PR and test more, but if you'd like to at least have the connection working you can try these changes.

**Comment by AlejandroFerrera** [comment]
Thank you again, @TPVallancourt! I managed to establish a connection. In our company, we implemented a workaround using a stack of (.NET + C# + Microsoft.SQL.Client + Dapper) to create a microservice, which handles all query requests from the Node backend. We're also leveraging the tedious fix as an alternative via environment variables.

**Comment by paretho** [comment]
@AlejandroFerrera, the other mssql node client msnodesqlv8 uses the ODBC driver under the hood. Using it, I manage to connect from our node backend to Fabric Lakehouse SQL endpoints. If you own the code connecting Fabric, switching client may be a viable option.

Unfortunately it's not for us since we also use third party libraries that depend on the native Javascript driver :(

**Comment by TPVallancourt** [comment]
Hi @cjcarpenter1 ! Haven't had the chance to fix the build issues that are stopping me form merging the fix into the library. The changes I made to the login7 payload are causing the build failures, but I don't know what is specifically the problem. For the time being, I've being using a [forked version of the node-mssql library](https://github.com/hightouchio/node-mssql) that has my Tedious changes in my project. Feel free to use this if you want to get a connection going, but beware that it has not been tested against anything other than a current Fabric instance (no idea if it works with old versions of SQLServer).

**Comment by anotherscotch** [comment]
Thank you for this @TPVallancourt - I've can confirm that this forked version works for One Lake / Fabric, so fingers crossed for a clean release 🤞

**Comment by mcrysler-ng** [comment]
Any updates as to when this might get merged?

**Comment by BrandonNoad** [comment]
@TPVallancourt any plans to pull in the latest upstream changes into your forks? I'm running into some issues trying to use the Token Credential functionality added in https://github.com/tediousjs/tedious/pull/1624 (described [here](https://github.com/tediousjs/node-mssql/issues/1745)).

I suspect it may be related to your forks not having pulled all the latest upstream changes. 

Thanks for the effort you've put in so far.

**Comment by JeremyDel** [comment]
Hi,

@TPVallancourt I have the following and testing with the newest released version 19.1.0 which I thought would fix the bug..
and still getting the same error:

Connection failed: ConnectionError: Connection lost - socket hang up
    at Connection.wrapSocketError (/home/jdelacro/projects/argenx/fabric_sql/node_modules/tedious/src/connection.ts:2386:14)
    at Socket.onEnd (/home/jdelacro/projects/argenx/fabric_sql/node_modules/tedious/src/connection.ts:2045:33)
    at Object.onceWrapper (node:events:633:28)
    ... 2 lines matching cause stack trace ...
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'ESOCKET',
  [cause]: Error: socket hang up
      at Socket.onEnd (/home/jdelacro/projects/argenx/fabric_sql/node_modules/tedious/src/connection.ts:2043:40)
      at Object.onceWrapper (node:events:633:28)
      at Socket.emit (node:events:531:35)
      at endReadableNT (node:internal/streams/readable:1698:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
    code: 'ECONNRESET'
  }
}


This is my code:

`
import { Connection, Request } from 'tedious';
import 'dotenv/config';

console.log('Tedious version:', require('tedious/package.json').version);


async function connectWithTedious() {
  try {

    const config = {
      server: process.env.SERVER,
      authentication: {
        type: 'azure-active-directory-service-principal-secret',
        options: {
          clientId: process.env.AZURE_CLIENT_ID,
          clientSecret: process.env.AZURE_CLIENT_SECRET,
          tenantId: process.env.AZURE_TENANT_ID,
        }
      },
      options: {
        database: process.env.DATABASE_NAME,
        encrypt: true,
        trustServerCertificate: false,
        port: 1433,
        connectTimeout: 30000,
        requestTimeout: 30000,
      }
    };

    const connection = new Connection(config);

    connection.on('connect', (err) => {
      if (err) {
        console.error('Connection failed:', err);
        return;
      }
      console.log('✅ Connected to database!');
      const request = new Request(
        'SELECT TOP 10 * FROM [AIFactory].[d_application]',
        (err, rowCount) => {
          if (err) {
            console.error('Query error:', err);
          } else {
            console.log(`${rowCount} rows returned`);
          }
          connection.close();
        }
      );

      request.on('row', (columns) => {
        console.log(columns);
      });

      connection.execSql(request);
    });

    connection.on('error', (err) => {
      console.error('Connection error:', err);
    });

    connection.connect();

  } catch (error) {
    console.error('Error:', error);
  }
}

connectWithTedious();
`

**Comment by bchoAshfords** [comment]
Hi, sorry I am new to tedious, thanks to TPVallancourt, I managed to connect to my Fabric Warehouse using his forked repo via Default Service Identity / Token.

I see that his PR has been merged so I assume I can use the official tedious library now. Would this also mean I can now use mssql lib to take advantage of 'connection pool'? Thank you all.

**Comment by arthurschreiber** [comment]
I merged the pull request I linked to earlier. Hopefully this will fix the issue for everyone. Please let me know if you still run into issues.
