### ISSUE TITLE
Intermittent lost connection to Azure SQL

### ISSUE THREAD

**Issue by tysjiang** [tediousjs/tedious#300]
I've been getting this error intermittently with tedious:

Fri Aug 14 2015 05:29:16 GMT+0000 (Coordinated Universal Time): Unaught exception: ConnectionError: Connection lost - read ECONNRESET
    at Connection.socketError (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:797:26)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:33:15)
    at Socket.emit (events.js:117:20)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)

The error stalls the entire node server and renders it unresponsive for around 10-15 minutes.  Afterwards, the server recovers by itself automatically.

I'm on the latest tedious 1.12.2 and using it with the tedious-connection-pool module 0.3.8
(although the issue is present prior to tedious 1.12.2 and has been happening in all the versions for the past few months)

What is interesting is that it seems like the issue happens much more frequently these days than before.  

I'm not sure if the above error message is helpful or not but if it's not, please inform me what other debug or log information I can get you good folks.  I've been testing out tedious and besides this particular showstopper issue for me, everything looks great.

As for servers, I'm using node 32bit v0.10.36 (although I've tested this with the latest node 12 and the issue is present there too) connecting to Azure SQL (v12 DB)

**Comment by palakautomation** [comment]
same here.
```
Application has thrown an uncaught exception and is terminated:
ConnectionError: Connection lost - read ECONNRESET
    at Connection.socketError (D:\home\site\wwwroot\node_modules\mssql\node_modules\tedious\lib\connection.js:797:26)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\mssql\node_modules\tedious\lib\connection.js:33:15)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
```

**Comment by arthurschreiber** [comment]
I'm not using Azure SQL and thus can not really help much on this topic without a lot more information on this. You could enable network logging and write all data out to a file so I could have a look at the network data.

**Comment by Reubend** [comment]
I'm having this same issue. The exact data returned is 
```
{ [ConnectionError: Connection is closed.]
      name: 'ConnectionError',
      message: 'Connection is closed.',
      code: 'ECONNCLOSED' }
```

I'm using Tedious through the node-mssql module, and so I normally have several Tedious connections open at the same time. I can try to get more info if you'd like, although I don't really know what I'm doing with this type of stuff. I'm not sure how to enable network logging; do you mean from the SQL Server?

**Comment by dmiddlecamp** [comment]
I seem to be hitting this while testing a nodejs app on "Azure Web Apps"
```
[ConnectionError: Connection lost - read ECONNRESET]
  name: 'ConnectionError',
  message: 'Connection lost - read ECONNRESET',
  code: 'ESOCKET' } ConnectionError: Connection lost - read ECONNRESET
    at Connection.socketError (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:795:26)
    at Socket.<anonymous> (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:33:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```


I'm using tedious version ~1.12.3, and mssql version 2.3.1

**Comment by Reubend** [comment]
Yeah, after updating, I'm still experiencing this issue. My setup is 
almost exactly the same, with an Azure SQL DB connected to an Azure Web App.

**Comment by lawrips** [comment]
Here's info I've learned from running in production - sharing here in the hope it's helpful.

There's a load balancer in Azure that has a default timeout of 4mins and will shut off idle connections. For other socket based services (e.g. mongo, imap, etc), I've had to set the keep-alive ping to be shorter than the 4 min mark (its ideal when the library supports this in the connection options as with mongo). So if this is the issue, one option is to implement that in tedious.

Another option worth investigating is this - https://azure.microsoft.com/en-us/blog/new-configurable-idle-timeout-for-azure-load-balancer/ although have not tried this myself (and not sure if it's related to sql).

Another option is to manage retries and reconnects in code. Here's a good article explaining some of the differences between azure sql vs sql and a recommended approach in c# which could be borrowed from: 

http://peterkellner.net/2011/01/21/sqlazure-connection-retry-problem-using-best-practices/

**Comment by arthurschreiber** [comment]
@lawrips That's quite interesting! Adding a keep-alive ping to tedious would be quite simple, as node.js exposes this on all sockets. I'll see if we can add this as on option for the next version of tedious.

**Comment by lawrips** [comment]
great ! love tedious - think this will be a nice addition

**Comment by christopheranderson** [comment]
:+1: Let me know if you need any help with this @arthurschreiber. I've definitely seen some issues with this.

**Comment by ashelley** [comment]
Hello, 

I'm also dealing with this issue.  In order to facilitate retry logic when a socket error occurs I needed to add a patch to tedious to ensure that a callback gets called when a request is in flight.

I'm still working on testing this patch but without it, the request callback is never called and your application has to implement it's own state on the connection to ensure that your request callback gets called when a socket error occurs.  

Note that this patch does not yet work with tedious-connection-pool because the connection pool closes the connection (changes the drivers state) before the driver can route to the proper state to call the request's callback.  The patch can be reviewed here:

https://github.com/pekim/tedious/issues/324

**Comment by arthurschreiber** [comment]
@lawrips I just checked the tedious code, and we already enable socket keepAlive, the same way e.g. mongodb drivers enable it. So a missing keepAlive can not be the cause of your lost connection issues.

**Comment by Reubend** [comment]
This is still occurring for me. I'm going to see if I can avoid the error by using a connection pool that swaps the connection every 30 seconds.

**Comment by jtmilne** [comment]
Please report back if that helps. I'm also having the same issue.

**Comment by Reubend** [comment]
Unfortunately, that didn't help. Even with frequent swapping of the connections, I still got the error. This leads me to believe that it has nothing to do with a timeout.

**Comment by lindo-jmm** [comment]
We're having a pretty hard time with this as well.

**Comment by christopheranderson** [comment]
Just a PSA, I get this message when I screw up something in my config/connection string. Not saying that's what happening, but thought it was worth mentioning.

**Comment by lindo-jmm** [comment]
Is it intermittent or do you get it immediately?

From: Christopher Anderson
Reply-To: pekim/tedious
Date: Tuesday, January 19, 2016 at 2:35 PM
To: pekim/tedious
Cc: Sean Lindo
Subject: Re: [tedious] Intermittent lost connection to Azure SQL (#300)


Just a PSA, I get this message when I screw up something in my config/connection string. Not saying that's what happening, but thought it was worth mentioning.

**Comment by christopheranderson** [comment]
Immediately, since it was broken. But lots of people searching for the error message find this issue.

**Comment by Reubend** [comment]
I don't think that's what's going on for me because the connection initially works and I can make requests through it  for a while. This error only appears after some time has passed (in my case).

**Comment by christopheranderson** [comment]
If you restart the app, does it work again? My first guess would be your running out of available connections to the SQL DB.

**Comment by ashelley** [comment]
@Reubend I think you already mentioned that you tried this but just wanted to reiterate the fact that you might need to ensure idle timeout on the connection pool is set to less than 4 minutes:

https://github.com/pekim/tedious-connection-pool#new-connectionpoolpoolconfig-connectionconfig

**Comment by Reubend** [comment]
Yes, if I restart the app, it works fine. I have the idle timeout set to only 30 seconds.

**Comment by ashelley** [comment]
I haven't yet implemented this myself in node but i wonder if you are hitting azure sql transient errors:

https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-csharp-retry-windows/

**Comment by Reubend** [comment]
I haven't written any code to deal with transient errors. That could definitely be the issue. However, I think it would be weird if my test DB has that many transient errors since I'm the only user sending requests.

**Comment by lindo-jmm** [comment]
Perhaps some kind soul would be willing to install SQL Server in a VM (or not, if you're on Windows) and verify if this still occurs or not. I have a feeling it's something with these Azure instances. I was getting this error before V12 as well.

**Comment by ashelley** [comment]
Transient errors on azure are typically "random" and not correlated to the number of requests.  I've seen them happen as low as one time per day but sometimes they can occur more frequently.   If your app still gets these errors if you don't have any connection pooling and create a new database connection on each request I would look at the transient error problem. In other words it might be worth trying to reproduce your problem without reusing any sockets.

**Comment by Reubend** [comment]
Interesting. I'll write up some code later tonight to see if it's indeed a transient error issue.

**Comment by sochka** [comment]
This is the first time I'm trying to connect node.js to mssql on Azure App Service and haven't had success. I'm always getting ```
ConnectionError: Connection lost - read ECONNRESET
    at ConnectionError (D:\home\site\wwwroot\node_modules\tedious\lib\errors.js:21:12)
    at Connection.socketError (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:575:56)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1256:8)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickDomainCallback (node.js:433:17)
    at process.<anonymous> (D:\home\site\wwwroot\node_modules\async-listener\index.js:19:15)```

For me this is a persistent issue, it never worked even for a minute. I'm sure there is no problem with configs or firewalls. I'm using loopback.js with it's loopback-connector-mssql module.

**Comment by lindo-jmm** [comment]
Out of curiosity, do you have the encrypt option set to true?

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Tue, Jan 19, 2016 at 4:31 PM -0800, "Oleksandr Sochka" <notifications@github.com<mailto:notifications@github.com>> wrote:


This is the first time I'm trying to connect node.js to mssql on Azure App Service and haven't had success. I'm always getting
ConnectionError: Connection lost - read ECONNRESET
at ConnectionError (D:\home\site\wwwroot\node_modules\tedious\lib\errors.js:21:12)
at Connection.socketError (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:575:56)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at emitErrorNT (net.js:1256:8)
at nextTickCallbackWith2Args (node.js:478:9)
at process._tickDomainCallback (node.js:433:17)
at process.<anonymous> (D:\home\site\wwwroot\node_modules\async-listener\index.js:19:15)

For me this is a persistent issue, it never worked even for a minute. I'm sure there is no problem with configs or firewalls. I'm using loopback.js with it's loopback-connector-mssql module.

-

**Comment by sochka** [comment]
Yeah, after writing my comment I went through the chain of libs and found out the comment in node-mssql which says you need to set enrypt to true. Which is not possible to do with loopback.js and therfore was not a part of their documentation. I will try a customly patched version now, will report here if that helps.

**Comment by jtmilne** [comment]
I get this error a couple times a day on all my node instances. I wrote a query wrapper to automatically retry on transient errors and it seems to work fine. Although it still is unsettling to see this happening.

**Comment by lindo-jmm** [comment]
Would you mind sharing a bit of pseudocode? I reached out on Twitter and apparently using a proxy was causing latency in all cases so MS removed this layer, but now if you hit your instance while its shifting you'll get hit with the error we're discussing (a transient error). All I've been able to gain is that "they're working to improve it". I believe the current accepted advice is to find some way to make your users wait 30s before retrying again =\

Please correct me if I'm misunderstanding anything!

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Tue, Jan 19, 2016 at 5:04 PM -0800, "Joel" <notifications@github.com<mailto:notifications@github.com>> wrote:


I get this error a couple times a day on all my node instances. I wrote a query wrapper to automatically retry on transient errors and it seems to work fine. Although it still is unsettling to see this happening.

-

**Comment by jtmilne** [comment]
Sure. Here's my singleton to handle db requests. I'm sure it could be greatly improved as Node/JS is not my primary language. http://pastebin.com/bxJHahfm

**Comment by sochka** [comment]
@lindo-jmm adding encrypt: true didn't help :( But I found this piece if code in loopback-connector-mssql:

```

  var connection = new mssql.Connection(this.settings, function(err) {
    if (err) {
      debug('Connection error: ', err);
      return callback(err);
    }
    debug('Connection established: ', self.settings.server);
    self.client = connection;
    callback(err, connection);
  });
```

The debug statements which I added are never executed.And probably for the reason - shouldn't they call .connect method with a callback separately? (according to these docs- http://patriksimek.github.io/node-mssql/#connection).

**Comment by sochka** [comment]
Currently this piece of code somehow deadlocks on Azure..

```
  console.dir(this.settings); // executed.
  /* Actual settings (with duplicate keys due to loopback's key remapping)
{ name: 'db',
  connector: 'mssql',
  host: 'shopimatedb.database.windows.net',
  port: 1433,
  database: 'shopimate',
  username: 'oleksandr@shopimatedb',
  password: 'MYSECRETPASSWORD', // not really
  encrypt: true,
  file: undefined,
  debug: true,
  server: 'shopimatedb.database.windows.net',
  user: 'oleksandr@shopimatedb' }
*/
  var connection = new mssql.Connection(this.settings, function(err) {
    if (err) {
      debug('Connection error: ', err); // never executed
      return callback(err);
    }
    debug('Connection established: ', self.settings.server); // never executed
    self.client = connection;
    callback(err, connection);
  });
  connection.on('error', function (err) {
    debug('error!', err); // never executed
    callback(err, connection);
  });
```
I believe it is not normal?

**Comment by Reubend** [comment]
Sorry for the delay. Tonight I tried adding some code to deal with transient errors, with good results so far. When the connection closed errors happen, I just keep retrying the request over and over. My test code for this is very primitive; Tedious doesn't seem to have a way to see the [error number](https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-error-messages/#bkmk_connection_errors) of a response, so I just assume all errors are transient. I'll post back here if my issues pop back up again. 

If it does turn out to be transient errors, I think we should add handling for them to Tedious. I could try writing the code and then send in a pull request.

**Comment by Reubend** [comment]
Today I saw the errors happen again despite the retry logic I put in last time. My app encountered the error and then retried the request once per second for about 10 minutes without success.

**Comment by robby** [comment]
I've also been seeing this error with azure. With the debug on, I see this.

```debug Connection lost - read ECONNRESET```

Which then ends up throwing an uncaught exception killing the process/worker.

**Comment by gkorland** [comment]
We're getting the following error tens of times a day (we're using tedious-connection-pool)

`database connection error:  {\"message\":\"Connection lost - read ECONNRESET\",\"code\":\"ESOCKET\"}`

**Comment by seanlindo** [comment]
@gkorland I'm using the same with an Azure SQL Instance, and we get buried in these every day. I've never seen anything like it.

**Comment by francolaiuppa** [comment]
I'm also getting the ECONNRESET error, output below: 

```
ConnectionError: Connection lost - read ECONNRESET
    at ConnectionError (/usr/src/myapp/node_modules/tedious/lib/errors.js:12:12)
    at Connection.socketError (/usr/src/myapp/node_modules/tedious/lib/connection.js:535:28)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1256:8)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
error: Forever detected script exited with code: 0
error: Script restart attempt #175
```
As you can see, the script restarted 175 times _in less than 48 hours..._ (approximately once every 16 minutes).

We also have this problem in production (which doesn't use Azure but an internal MSSQL farm)
I'll keep researching to see if I can fix it, so far I thought in forcing a reconnect every 5 minutes but I don't think that will solve it... maybe running a dummy query on timer just to keep the connection alive?
Any ideas? 
Thanks in advance!

**Comment by francolaiuppa** [comment]
Guys I don't know if this is the right fix/hack or not, but I've been reading around and it seems the Azure SQL Databases are behind a load balancer (which does not surprise me at all). 
Some load balancers reset the connection rather than closing it (hence why we get the `ECONNRESET`). Since we had no `error` handler defined, it threw an `Exception` which in turn made the whole app crash!

To fix it, I've added

```
 connection = new Connection(tediousConfig);
 connection.on('error',function(err) {
    // of course here you need to check if it wasn't other kind 
    // of error, I've redacted it for brevity
    console.log(err);
    console.log('The app is still running as this error is recoverable');
 });
```

I've tested it by running a method that access the database right after the `ECONNRESET` happened and I was able to see the data without any problems!
If anyone here can confirm this fixes their problem, I think we'll be closer to a final solution...

Hope it helps you!

**Comment by Reubend** [comment]
Franco, wouldn't that have been solved by the connection idle timeout? For instance, if each connection lasts for only 30 seconds, then it seems that the load balancer should not reset a connection that quickly.

**Comment by seanlindo** [comment]
@Reubend Did you ever share your code you used when positing your comment a few messages above?

**Comment by Reubend** [comment]
The code I used was very simple, it just used the built in error callback of a request to close the connection and then open it again before retrying the request.

**Comment by francolaiuppa** [comment]
@Reubend could you paste some code so I understand what are you referring to when you say the connection idle timeout? I'm using Tedious with Sequelize and I'm managing the connection idle timeouts using a pool from within sequelize (let me know if you want the full example).

**Comment by Reubend** [comment]
@francolaiuppa Sure! I'm using the node-mssql with tedious, so the code will look a little bit different from yours, but the idea is the same.

```
var databaseConfig = {
    user: 'redacted',
    password: 'redacted',
    server: 'redacted',
    database: 'redacted',
    connectionTimeout: 10000,
    requestTimeout: 10000,
    
    pool: {
        max: 10,
        min: 0,
        idleTimeoutMillis: 14999
    },
    
    options: {
        encrypt: true
    }
}

var database = new sql.Connection(databaseConfig, function (err) {
    if (err) {
        console.log("An error occurred while trying to connect to the database:");
        console.log(err);
        process.exit();
    } else {
        console.log("Connected to the database.");
        initializeServer();
    }
});
```

**Comment by gkorland** [comment]
@francolaiuppa you're right about your analysis (I confirmed it with the Azure team)
The only real solution to make sure their LB won't shutdown the connection after 30min is to "ping" the connection. We're doing it by firing a lightweight query on idle connections every 5min (select 1)

**Comment by jtmilne** [comment]
@gkorland Shouldn't the idleTimeoutMillis setting on the pool prevent resetting the connection before the LB times out? I wouldn't think that a ping query is necessary as long as you set the idleTimeoutMillis to an appropriate value.

**Comment by francolaiuppa** [comment]
@Reubend thanks for sharing the code. I've the same config for `pool` but I was still getting the `ECONNRESET`. 
Regarding the connection retry, I've a very similar code, but that's a different issue.

@gkorland Glad to hear you could confirm it with the Azure team, thanks for taking time to do so! 
I also thought of making the `SELECT 1` query on a timer but it seemed hacky... guess we'll have to do that to avoid the `ECONNRESET` altogether until another solution pops up :)
Just wanted to add that even without running the select query on timer, I was still able to use the app without problems by just catching the `ECONNRESET` error and outputting a console log (as shown on my previous https://github.com/pekim/tedious/issues/300#issuecomment-216603746)

@jtmilne hey there, I've tried changing the values for the timeout before but I'll still get the `ECONNRESET` sooner or later. In my case is after some 16 minutes. Have you measured how long it takes for you?

**Comment by seanlindo** [comment]
@francolaiuppa It looks like there's two different solutions in play, can you confirm?

* Catch the ECONNRESET error for those of us who are not; Everything with the app is actually fine.

* Ping the database at some internal to prevent it from being reset by the LB

**Comment by francolaiuppa** [comment]
@seanlindo I can confirm the `ECONNRESET` solution.
Regarding the ping database solution (i.e running a `SELECT 1` query), it should work too, although I haven't tested it. 
I can try this approach next week if I get some time at work, but in the meantime, maybe you can run that test and let us know? 

If we can confirm that the ping database solution works, I can create a PR to enable this feature ONLY for Azure-like databases, although I'm open to cleaner solutions

Thanks!

**Comment by seanlindo** [comment]
@francolaiuppa Like you, I'm also using `node-mssql`

Is there a better way to "recover" the connection when an error occurs? Is that a cleaner way of dealing with this issue?

I followed it's documentation by attaching a listener and added this bit of code to my factory function (I should be checking the error in a better way, bear with me!):

    sql.on('error', function (err) {
        if(err.message == "Connection lost - read ECONNRESET") {
          Logger.logInfo('ECONNRESET-- not crashing the application');
        }
        else if (err.message == "Connection lost - read ETIMEDOUT") {
          Logger.logInfo('ETIMEDOUT-- not crashing the application');
        }
    });

Instead of simply logging the error, is there a way to "heal" the connection and return it? I should probably have this conversation in the `node-mssql` repo, but I've noticed Google searches bring up this thread. 

Perhaps I'll inquire there as well.

**Comment by Reubend** [comment]
I will do a test using the `SELECT 1` query on a timer. If it ends up working, I'll post back here. I still haven't found any testing procedure that forces this bug to appear, so it's hard for me to test properly.

**Comment by GISDev01** [comment]
We are also experiencing this issue as well. This app is a typical NodeJS/Express API that queries data out of a large AzureSQL Database using this Tedious driver. 
Our workaround fix for now is catching the error as mentioned above, but it would be great if this was built in to the library. I'll see if I can find time to dig into this repo and put a patch in.

**Comment by Reubend** [comment]
Hey everybody, apologies for the huge delay since my last post. I tested the `SELECT 1` query pinger as a way of avoiding this issue, and I can confirm that it does *not* work for me. I've tried catching the error before without much success, but based on the post by @GISDev01 maybe I will try again with some different code.

**Comment by Reubend** [comment]
My error catching code didn't seem to work either. Am I catching them incorrectly? Here's my code, based on the last few suggestions:

```
//Ping the database constantly
setInterval(function () {
    var updateRequest = database.request();
    var statement = "SELECT 1";
    updateRequest.query(statement, function (err, recordset) {
        if (err) {
            console.log("Database failure.");
        }
    });
}, 9000);

var initTime = process.hrtime()[0];

//Catch connection reset errors and reconnect to the database
sql.on('error', function (err) {
    if (err.message == "Connection lost - read ECONNRESET") {
        console.log("Connection reset bug appeared.");
        console.log("It took " + process.hrtime()[0] - initTime);
    }
    database.close();
    database = new sql.Connection(databaseConfig, null);
});
```

**Comment by francolaiuppa** [comment]
@Reubend you can try to `console.log(err)` and then see what _exact_ string you get for `err.message`. 

Also note that you don't need to manually reconnect (tedious *should* do it for you) only catching the error and doing nothing (i.e console logging) prevents `tedious` from breaking your app. 
Again... it is not a solution but a hack...

Something that I haven't tested is whether the SQL query gets retried when the app reconnects :fearful:

**Comment by Reubend** [comment]
Thanks @francolaiuppa for the tip! I'm going to remove the reconnection code and see if that helps.

**Comment by trevorfrese** [comment]
@Reubend did you end up solving this?

**Comment by realpunk** [comment]
Anyone has a working solution for this ?

**Comment by stern-shawn** [comment]
Wondering if there is any solution to this besides the previously mentioned logging hacks :)

**Comment by v-suhame** [comment]
Fix for transient failure (#574) submitted by @tvrprasad is already in master. Changes should be out in next npm release.

**Comment by Chris-CBD** [comment]
When is this new npm release coming out?  I am struggling with this issue and it looks like it's been a problem for years.

**Comment by jpalo** [comment]
When using "SELECT 1" ping workaround, I get intermittent "ConnectionError: Failed to connect to xyz.database.windows.net:1433 in 10000ms" errors _in the ping_. ECONNRESETs seem to have stopped, though.

**Comment by v-suhame** [comment]
@jpalo Can you test with `tedious@2.1.1`? It has the fix for intermittent failure :)

**Comment by v-suhame** [comment]
Fixed by #574. Closing this issue. Feel free to open it if you face this issue with version >= `tedious@2.1.1`.

**Comment by Kannaj** [comment]
we're still seeing random connection resets on our end unfortunately.

the tedious version we're using is `v2.2.1` . so i dont believe the update has resolved the issue (at least for us)

We're using stored procedures to handle a majority of the SQL queries. some of these queries and INSERT statements and therefore dont return anything. in cases such as these , do we have to manually close the connection between node and sql? something like `connection.close()` ?

Is there any other suggestion that you can provide?

**Comment by v-suhame** [comment]
@Kannaj Even if your TSQL doesn't return anything, `Request` will emit either `done`, `doneInProc` or `doneProc` event, based on SQL query. You can use those events to close the connection. And, yes, your application has to decide when to close the connection and call `connection.close()` manually.

Regarding the connection reset issue, can you share more details? How is connection reset related to closing the connection? Just to confirm, does this involve Azure SQL Server?

**Comment by arthurschreiber** [comment]
@Kannaj Hey there! 👋 

I'm really sad to hear you're facing trouble with tedious. As @v-suhame mentioned, your issue description is unfortunately not enough for us to debug this. It'd be great if you could help us help you! 😄

* Which version of SQLServer do you connect to?
* How many requests does your application execute, and how often do you see connection resets?

* Do you have multiple processes that connect to the SQL Server? Is there only a single connection open per process? Do different processes (or different connections in a single process) see the reset at the same time?
* Is there a stack trace or anything that helps to pinpoint a bit where the connection reset happens?
* Does the connection reset happen during query execution or during times where no query is run?
* How much time passes between the llast query execution and the connection reset?
* Can you check the SQL Server logs and see if there's anything in there that might be helpful in there?

If anyone else in this thread can answer these questions, feel free to do so as well! 👍

**Comment by jtmilne** [comment]
I used to get this error using Azure SQL Server, but solved it by implementing automatic retries for any requests that failed with a transient error (I keep retrying until my TTL of 1 min expires). Note: each time you call query or execute on a request a new connection is acquired from the pool so this should solve any problems with individual connections that are acting up. Here is the code I use to test for transient errors. 

```
function isErrorTransient(err) {
    var arrayTransientErrors = ['ENOCONN', 'ENOTOPEN', 'ESOCKET', 'ENOTFOUND', 'ENETDOWN', 'EADDRNOTAVAIL', 'ETIMEOUT', 'ETIMEDOUT'];
    return (err && 'code' in err && arrayTransientErrors.indexOf(err.code) > -1);
}
```

It would be very nice if the library provided an option on Requests to automatically retry with a new connection when a transient error occurred (with a TTL parameter).

**Comment by v-suhame** [comment]
@jtmilne Thanks for sharing the workaround 👍 

@jtmilne @Kannaj Can you verify if the error occur only during idle connection (in the newer version of driver)? That would be of great help, we can rule out or consider idle connection resiliency based on it.
>an idle connection is the one that is active (opened, but not in the pool) but it’s not executing a command or waiting for data.

From MSDN doc for other Driver,
> Connection resiliency is the principle that a broken idle connection can be reestablished, within certain constraints. If a connection to Microsoft SQL Server fails, connection resiliency allows the client to automatically attempt to reestablish the connection.

**Comment by jtmilne** [comment]
@v-suhame Sorry but I wrote this fix 2 years ago so I don't remember the details of the errors.

**Comment by Kannaj** [comment]
Thanks for your prompt response guys

@v-suhame  - my thinking is that the connection is being reset by Sql because the connection still persists after the procedure is executed. heres' the structure of my SQL queries

```javascript
exports.do = function(type, params, callback){
    var conn = new Connection(connectionConf);
    conn.on('connect', function(err) {
        // if a connection error occured, then fail immediately
        if (err) {
            logger("warn", "db", "cannot connect to sql db", null, {"err":err});
            callback(err);
        }
        else
        {
            var request = new Request(type, function(err, rowCount){
                if (err) {
                    callback(err);
                }
                else if (rowCount == 0) {
                    callback();
                }
            });

            // set the parameters based on the request that was supposed to be executed
            switch(type) {
                case "procName":
                    request.addParameter('email', TYPES.VarChar, params[0]);
                    conn.callProcedure(request);                                    
                    break;            
                }

            request.on('row', function(columns) {
                var returnObject = {};

                // iterate and map the object to each column - the column name is in the metadata object
                columns.forEach(function(column){
                    returnObject[column.metadata.colName] = column.value;
                });

                // return with an error if the error occured and was caught by the procedure 
                if (columns[0].metadata.colName == 'error') {
                    callback(returnObject);
                }

                // return with the result set given by the procedure
                else {
                    callback(null,returnObject);
                }
            })
        }
    });

    conn.on('error', function(err){
        logger("warn", "db", "exception in tedious", null, {"err":err});
    })
};
```

Am i missing something out? 

@arthurschreiber 
 - Which version of SQLServer do you connect to?
12.0.2000.8

- How many requests does your application execute, and how often do you see connection resets?

Connection resets are quite random and hard to measure unfortunately. but we see one happen every few hours. regarding number of queries sent - we have around 10-12 requests happen per session

- Do you have multiple processes that connect to the SQL Server? Is there only a single connection open per process? Do different processes (or different connections in a single process) see the reset at the same time?

We have only one process connected to the SQL server

- Is there a stack trace or anything that helps to pinpoint a bit where the connection reset happens?
```
ConnectionError: Connection lost - read ECONNRESET
    at ConnectionError (D:\home\site\wwwroot\node_modules\tedious\lib\errors.js:12:12)
    at Connection.socketError (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:873:28)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2018-01-08T07:50:34.791Z - error: uncaughtException: Connection lost - read ECONNRESET date=Mon Jan 08 2018 07:50:34 GMT+0000 (Coordinated Universal Time), pid=7068, uid=null, gid=null, cwd=D:\home\site\wwwroot, execPath=D:\Program Files (x86)\nodejs\8.9.3\node.exe, version=v8.9.3, argv=[D:\Program Files (x86)\nodejs\8.9.3\node.exe, D:\home\site\wwwroot\server.js], rss=37429248, heapTotal=38248448, heapUsed=34221824, external=33298857, loadavg=[0, 0, 0], uptime=undefined, trace=[column=12, file=D:\home\site\wwwroot\node_modules\tedious\lib\errors.js, function=ConnectionError, line=12, method=null, native=false, column=28, file=D:\home\site\wwwroot\node_modules\tedious\lib\connection.js, function=Connection.socketError, line=873, method=socketError, native=false, column=20, file=events.js, function=emitOne, line=121, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickDomainCallback, line=218, method=_tickDomainCallback, native=false], stack=[ConnectionError: Connection lost - read ECONNRESET,     at ConnectionError (D:\home\site\wwwroot\node_modules\tedious\lib\errors.js:12:12),     at Connection.socketError (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:873:28),     at emitOne (events.js:121:20),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickDomainCallback (internal/process/next_tick.js:218:9)]
```

- Does the connection reset happen during query execution or during times where no query is run?
This again is quite varied , but usually theres a reset happening for queries that were carried out several minutes ago

- How much time passes between the llast query execution and the connection reset?
Not sure on this unfortunately as its quite varied

- Can you check the SQL Server logs and see if there's anything in there that might be helpful in there?
Will get back to you on this.

**Comment by Kannaj** [comment]
@v-suhame , @arthurschreiber - any idea about this? We currently out of solutions. :( 

Any help or advice would be great

**Comment by v-suhame** [comment]
@Kannaj Sorry for the delayed response. Is there any reason for not closing the connection after `Request` completes? If you're not reusing the connection, it is best to close it after use to release resources both in Server and Client side.
If you want the connection to stay open, maybe you can try https://github.com/tediousjs/tedious/issues/300#issuecomment-355672780 as temporary solution, till we get to the root of it. 

Is that an on-premise SQL Server or Azure  SQL Server? 
Do share the SQL Server logs when you get them.

**Comment by mattyglover** [comment]
I am getting this issue also using the latest tedious, v2 of the function app runtime on Azure and MS SQL server. I'm thinking the only solution might be to write a sync loop to try up to 5 times to connect before crashing. Anyone else found a solution?

**Comment by marcindabrowski** [comment]
I also got this error just after starting bulk load.
And the cause was that I tried to insert text which had more characters than column allowed.
When I altered column it started to work.

**Comment by wy193777** [comment]
Got same error when using newest tedious version with typeorm. It works half years ago, not sure why.

**Comment by wy193777** [comment]
Actually it's not intermittent. A very stable behavior.

**Comment by MichaelSun90** [comment]
Hi @wy193777, 
Can you provide a reproduce script with the typeorm? I want to try it on my side, see if I got the same behavior. Thanks!

**Comment by dfenerski** [comment]
So... how do you close a connection? :D and why do connections 'crash' and go to sleep? no clear fix found.

**Comment by cjorge** [comment]
There can be two reasons for this issue to happen, both most likely linked to cloud based SQL.

The most likely reason is to implement code for a persistent connection in your database connection code. Probably something similar to:

`if (connPoolPromise) return connPoolPromise;`

You persist the promise but the database, if the connection (by any reason) has been rejected, cannot connect it will proceed to try to make the request using a non existent connection and throw an error Uncaught exception: ConnectionError: Connection lost - read ECONNRESET. This error would be thrown on your REQUEST and not on your CONNECTION. I'm assuming most of the cases will be due to this.

You could have transient errors on connection but this would be very unlikely... Still, a retry approach would be wise regardless. You can try this locally by trying to connect to the database by turning your wifi off and on... Ideally when you can't connect you should retry a couple of times with a few seconds interval. Something similar to this should so the trick:

```
async function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

let connPooPromise = null;
let retries = 0;
while(retries<10){
        connPoolPromise = await CreatePool();
        if (connPoolPromise!==null) break;
        retries++;
        await sleep(2000);
    }
return connPoolPromise;
```
