### ISSUE TITLE
Problem with date strings

### ISSUE THREAD

**Issue by PatrLind** [tediousjs/tedious#339]
I'm trying send date strings to the database and I'm having some issues.

This is my sample query:
`SELECT @p0 AS a`
And the parameter is:
`'2015-10-31 00:00:00'`
I have tried these datatypes with similar result: DateTime, DateTime2, DateTimeOffset

This is the error message:

```
c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\node_modules\tedious\lib\data-type.js:1514
        var offset = -parameter.value.getTimezoneOffset();
                                      ^
TypeError: undefined is not a function
    at Object.writeParameterData (c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\node_modules\tedious\lib\data-type.js:1514:39)
    at new RpcRequestPayload (c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\node_modules\tedious\lib\rpcrequest-payload.js:95:12)
    at Connection.execSql (c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\node_modules\tedious\lib\connection.js:764:66)
    at _execNextInQueue (c:\Klocktornet\DISEServerWebUI\node_modules\any-db-mssql\index.js:606:11)
    at process._tickCallback (node.js:355:11)
```

The issue seems to be that the value is converted from a string to an integer in the validate method in data-type.js. The value after the conversion is 1446246000000. It seems to me that this should really be a Date object and not a number. 

I can work around this bu sending in real Date objects, but I still think this is an issue that should be solved.

**Comment by arthurschreiber** [comment]
Can you do me a favor and check if you also face this issue with version `1.11.5`?

And you're right, the parameter handling code is a bit iffy.

**Comment by Ramzeus** [comment]
Yes, I cannot see any difference with 1.11.5

**Comment by arthurschreiber** [comment]
Ok, thanks for letting me know. I just wanted to verify this was not a regression introduced in `1.12`/`1.13`

**Comment by jimmont** [comment]
`parameter.value.getTimezoneOffset is not a function` this method is being called on a type of object which is not a Date and throwing an error, see (npm 2.6.2) lib/data-types/smalldatetime.js near line 31.

To reproduce add a parameter that is a SmallDateTime

```
npm ls
├─┬ tedious@2.6.2

error:
(node:36545) UnhandledPromiseRejectionWarning: TypeError: parameter.value.getTimezoneOffset is not a function
    at Object.writeParameterData (/path/node_modules/tedious/lib/data-types/smalldatetime.js:31:37)
    at new RpcRequestPayload (/path/node_modules/tedious/lib/rpcrequest-payload.js:95:12)
    at Connection.execSql (/path/node_modules/tedious/lib/connection.js:1332:51)
    at Promise (/path/node_modules/tedious-wrapper/index.js:216:28)
    at <anonymous>
```

**Comment by bugg2844** [comment]
This only occurs when options.useUTC is set to false, and the parameter value is something tedious needs to parse e.g. a string containing a date.  Tedious uses Date.parse to parse the string, which returns a number of milliseconds, then later tries to call getTimezoneOffset on that value.

**Comment by bugg2844** [comment]
Appears to be caused by: https://github.com/tediousjs/tedious/commit/f360b093d731a7ec2ef63469130be4bef89c39f2

**Comment by bugg2844** [comment]
Looks like https://github.com/tediousjs/tedious/pull/677/files will resolve it.
