### ISSUE TITLE
BulkLoad do not validateParameters()

### ISSUE THREAD

**Issue by Llorx** [tediousjs/tedious#421]
Simple as that. If I add a 1234123 value to a SmallInt, I receive this error:

`TypeError: value is out of bounds
    at checkInt (buffer.js:716:11)
    at Buffer.writeInt16LE (buffer.js:874:5)
    at WritableTrackingBuffer.writeInt16LE (lib\mssql\node_modules\tedious\lib\tracking-buffer\writable-tracking-buffer.js:165:19)
    at Object.writeParameterData (lib\mssql\node_modules\tedious\lib\data-type.js:108:23)
    at BulkLoad.addRow (lib\mssql\node_modules\tedious\lib\bulk-load.js:126:16)
    at lib\mssql\node_modules\mssql\lib\tedious.js:688:22
    at Transaction.queue (lib\mssql\node_modules\mssql\lib\main.js:1010:9)
    at Request._acquire (lib\mssql\node_modules\mssql\lib\main.js:1178:33)
    at Request.TediousRequest.bulk (lib\mssql\node_modules\mssql\lib\tedious.js:609:21)
    at Request._bulk (lib\mssql\node_modules\mssql\lib\main.js:1457:53)`

Following the source code, BulkLoad do not validate anything before calling AddRow.

**Comment by arthurschreiber** [comment]
#677 will fix this.

**Comment by Llorx** [comment]
Can't close as we are not following the project were we used tedious so can't check if is fixed.
