### ISSUE TITLE
NodeJS 6.4.0 Empty String Range Error

### ISSUE THREAD

**Issue by spanditcaa** [tediousjs/tedious#431]
We are seeing errors (stack below) from tedious in our API under node 6.4 due to this new bug:

https://github.com/nodejs/node/issues/8127

It sounds like this will be fixed in node, a fix isn't necessary in tedious but I wanted to share the finding.

````
RangeError: Offset is out of bounds
    at RangeError (native)
    at Buffer.write (buffer.js:778:21)
    at WritableTrackingBuffer.writeString (\node_modules\tedious\lib\tracking-buffer\writable-tracking-buffer.js:216:38)
    at Login7Payload.addVariableDataString (\node_modules\tedious\lib\login7-payload.js:228:25)
    at Login7Payload.createVariableData (\node_modules\tedious\lib\login7-payload.js:194:12)
    at new Login7Payload (\node_modules\tedious\lib\login7-payload.js:111:25)
    at Connection.sendLogin7Packet (\node_modules\tedious\lib\connection.js:602:21)
    at Connection.message (\node_modules\tedious\lib\connection.js:1054:16)
    at Connection.dispatchEvent (\node_modules\tedious\lib\connection.js:519:45)
    at MessageIO.<anonymous> (\node_modules\tedious\lib\connection.js:439:23)
    at emitNone (events.js:86:13)
    at MessageIO.emit (events.js:185:7)
    at ReadablePacketStream.<anonymous> (\node_modules\tedious\lib\message-io.js:92:15)
    at emitOne (events.js:96:13)
    at ReadablePacketStream.emit (events.js:188:7)
    at readableAddChunk (\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:198:18)
    at ReadablePacketStream.Readable.push (\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:157:10)
    at ReadablePacketStream.Transform.push (\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at ReadablePacketStream._transform (\node_modules\tedious\lib\message-io.js:57:16)
    at ReadablePacketStream.Transform._read (\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at ReadablePacketStream.Transform._write (\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:313:64)
````

**Comment by mkraft** [comment]
I'm experiencing the same bug.

**Comment by justinschuldt** [comment]
Just updated to node 6.4.0, am getting this too

**Comment by spanditcaa** [comment]
https://github.com/nodejs/node/pull/8154 is the fix and should be in node 6.4.1

**Comment by arthurschreiber** [comment]
It looks like there won't be any 6.4.1 release, but 6.5.0 will get released soon and contains the fix for this issue. See https://github.com/nodejs/node/pull/8253

**Comment by spanditcaa** [comment]
Working normally with node 6.5.0.
