### ISSUE TITLE
hundreds of "Error: Unknown type: xx" errors when switching between two slightly different versions of SQL 2008 R2

### ISSUE THREAD

**Issue by jcollum** [tediousjs/tedious#469]
```
$ cat node_modules/tedious/package.json | grep version
  "version": "1.14.0"
$ node --version
v6.9.1
```

Typical call stack: 

```
Error: Uncaught error: Unknown type: 50
    at Parser.parseTokens (/opt/data/apps/cdk/datalake-utilities/node_modules/tedious/lib/token/stream-parser.js:99:30)
    at Parser._transform (/opt/data/apps/cdk/datalake-utilities/node_modules/tedious/lib/token/stream-parser.js:72:14)
    at Parser.Transform._read (/opt/data/apps/cdk/datalake-utilities/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Parser.Transform._write (/opt/data/apps/cdk/datalake-utilities/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/opt/data/apps/cdk/datalake-utilities/node_modules/readable-stream/lib/_stream_writable.js:319:64)
    at writeOrBuffer (/opt/data/apps/cdk/datalake-utilities/node_modules/readable-stream/lib/_stream_writable.js:308:5)
    at Parser.Writable.write (/opt/data/apps/cdk/datalake-utilities/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at Parser.addBuffer (/opt/data/apps/cdk/datalake-utilities/node_modules/tedious/lib/token/token-stream-parser.js:50:26)
    at Connection.sendDataToTokenStreamParser (/opt/data/apps/cdk/datalake-utilities/node_modules/tedious/lib/connection.js:644:37)
    at Connection.data (/opt/data/apps/cdk/datalake-utilities/node_modules/tedious/lib/connection.js:1172:21)
    at Connection.dispatchEvent (/opt/data/apps/cdk/datalake-utilities/node_modules/tedious/lib/connection.js:519:45)
    at MessageIO.<anonymous> (/opt/data/apps/cdk/datalake-utilities/node_modules/tedious/lib/connection.js:436:16)
    at emitOne (events.js:96:13)
    at MessageIO.emit (events.js:188:7)
    at ReadablePacketStream.<anonymous> (/opt/data/apps/cdk/datalake-utilities/node_modules/tedious/lib/message-io.js:90:13)
    at emitOne (events.js:96:13)
```

Sample of errors: 

```
error: Unknown type: 50
Error: Unknown type: 0
Error: Unknown type: 161
Error: Unknown type: 8
Error: Unknown type: 111
```

and so on. This is happening when I change from a known working server with this `@@Version`: 

```
    Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64) 
    Apr  2 2010 15:48:46 
    Copyright (c) Microsoft Corporation
    Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```

to this one: 

```
 Microsoft SQL Server 2008 R2 (SP2) - 10.50.4270.0 (X64) 
    Nov 30 2012 17:11:43 
    Copyright (c) Microsoft Corporation
    Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```

Upgrading the database (in any way) is probably a non-starter. 

Any help appreciated. This kills a project that I've been working on for two months. I'm concerned.

**Comment by arthurschreiber** [comment]
This should be fixed with the latest code in master, or in the next release.

**Comment by jcollum** [comment]
I forgot to update: one of the columns in the view was a sql_variant type (an ipaddress from @@serverproperties or something like that, I don't have it in front of me). I edited the view to turn that into a varchar and the problem went away.

**Comment by tvrprasad** [comment]
This should be fixed by https://github.com/tediousjs/tedious/commit/4a0b5dadf5d17d7ad91d4817356dd1cff8887fb0
