### ISSUE TITLE
request.transformIntoExecuteSqlRpc(); error when inserting row

### ISSUE THREAD

**Issue by z6tanker** [tediousjs/tedious#488]
Hey so whenever I try to insert a row with the following SQL it seems to be throwing an error saying:

I'm not sure if this is an SQL issue or a Tedious issue but I thought I'd just post it here. I'm a bit of a novice to thanks in advance!

```
C:\Users\John\Source\Repos\TestApp\TestApp\Console Test App\node_modules\tedious\lib\connection.js:717
      request.transformIntoExecuteSqlRpc();
              ^

TypeError: request.transformIntoExecuteSqlRpc is not a function
    at Connection.execSql (C:\Users\John\Source\Repos\TestApp\TestApp\Console Test App\node_modules\tedious\lib\connection.js:717:15)
    at addTimestamp (C:\Users\John\Source\Repos\TestApp\TestApp\Console Test App\app.js:144:16)
    at Request.userCallback (C:\Users\John\Source\Repos\TestApp\TestApp\Console Test App\app.js:101:21)
    at Request.module.exports._EventEmitter.Request.callback.callback (C:\Users\John\Source\Repos\TestApp\TestApp\Console Test App\node_modules\tedious\lib\request.js:33:27)
    at Connection.message (C:\Users\John\Source\Repos\TestApp\TestApp\Console Test App\node_modules\tedious\lib\connection.js:1179:27)
    at Connection.dispatchEvent (C:\Users\John\Source\Repos\TestApp\TestApp\Console Test App\node_modules\tedious\lib\connection.js:519:45)
    at MessageIO.<anonymous> (C:\Users\John\Source\Repos\TestApp\TestApp\Console Test App\node_modules\tedious\lib\connection.js:439:23)
    at emitNone (events.js:86:13)
    at MessageIO.emit (events.js:185:7)
    at ReadablePacketStream.<anonymous> (C:\Users\John\Source\Repos\TestApp\TestApp\Console Test App\node_modules\tedious\lib\message-io.js:92:15)
Press any key to continue...
```
Here is my code:
```
function addTimestamp(carID, locID) {
    addCarTimeStamp = new Request(`INSERT INTO [dbo].[time_stamps] ([timestamp_id], [timestamp], [car_id], [location]) VALUES (NEWID(), SYSUTCDATETIME(), '${carID}', '${locID}')`,
        function (err) {
            if (err) {
                console.log(err);
            } else {

            };
        });

    connection.execSql(addTimestamp);
}
```

**Comment by tvrprasad** [comment]
User error :-)

This:
>     connection.execSql(addTimestamp);

Should be:
>     connection.execSql(addCarTimeStamp );
