### ISSUE TITLE
Socket creation error on Node version 7.7.2

### ISSUE THREAD

**Issue by yasen-atanasov** [tediousjs/tedious#532]
Hi,

Upgrading to node v.7.7.2 on Windows results in this error when trying to use Tedious:
```
events.js:307
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at Socket.once (events.js:307:11)
    at Socket.connect (net.js:943:10)
    at Connection.connectOnPort (c:\wrk\xogito\ussquash\usq_api\node_modules\tedious\lib\connection.js:429:19)
    at Connection.connect (c:\wrk\xogito\ussquash\usq_api\node_modules\tedious\lib\connection.js:402:21)
    at Connection.initialiseConnection (c:\wrk\xogito\ussquash\usq_api\node_modules\tedious\lib\connection.js:77:12)
    at Connection.enter (c:\wrk\xogito\ussquash\usq_api\node_modules\tedious\lib\connection.js:975:19)
    at Connection.transitionTo (c:\wrk\xogito\ussquash\usq_api\node_modules\tedious\lib\connection.js:508:33)
    at new Connection (c:\wrk\xogito\ussquash\usq_api\node_modules\tedious\lib\connection.js:66:10)
```

Going to row 429 in tedious/lib/connection.js and adding an empty function as a second parameter to the `socket.connect` call resolves the issue. I'm not sure whether this is a nodejs or tedious problem.

For the time being I've downgraded node to 7.7.1

**Comment by arthurschreiber** [comment]
I think this will be fixed with the upcoming `1.15.0` release.

**Comment by vhain** [comment]
If it's Node 7.7.2, can be bug of Node. If yes, it should be solved by https://github.com/nodejs/node/pull/11762

**Comment by BarryCarlyon** [comment]
I have the some problen with node 7.7.0 and 7.7.2 and it's affecting a LOT of modules…

(Redis for example)

**Comment by jdanyow** [comment]
For me this is an issue in node v7.7.2. It worked in node v7.7.1.

In connection.js, connectOnPort calls socket.connect with one arg:

![image](https://cloud.githubusercontent.com/assets/1306747/23911909/735c5198-089b-11e7-8248-fca59d8ae590.png)

But socket.connect can't handle the second arg being undefined:

![image](https://cloud.githubusercontent.com/assets/1306747/23912009/c2779008-089b-11e7-8a41-6dbc381c8737.png)

Appears to be fixed by:

https://github.com/nodejs/node/commit/c6cbbf92630069f7f7c29e4dff2f622d48d741d5

**Comment by tvrprasad** [comment]
This issue does not exist in Tedious 1.15.0 which got released just a few days back. You may want to upgrade.
