### ISSUE TITLE
Callback is not a function

### ISSUE THREAD

**Issue by Jorgeee1** [tediousjs/tedious#667]
Hello,  I have this code which is mistaken somewhere (although I somehow can't spot it). The error is "TypeError: callback is not a function", I have tried many ways to solve it, but any of them has worked, I hope you can take a look at the code and help me.

```
  'xxx' : function(data, callback){
    var connection = new Connection(config);
    var newdata = [];
    var dataset = [];
    connection.on('connect', function(err) {

        var sql = "SELECT * FROM table";

        var Request = require('tedious').Request;
        var request = new Request(sql, function (err, rowCount) {
            if (err) {
                callback(err);
            } else {
                if (rowCount < 1) {
                    callback(null, false);
                } else{
                  callback(null, newdata);
                }
            }
        });
   
        request.on('row', function(columns) {
            columns.forEach(function(column) {
                   dataset.push({
                       col: column.metadata.colName,
                       val: column.value
                   });
            });
            newdata.push(dataset);
        });
        connection.execSql(request);
    });
}
```

Thank you very much in advance.

**Comment by arthurschreiber** [comment]
Heya @Jorgeee1!

On a first look, I don't see anything obviously wrong, but it's really hard to pinpoint the issue without the full error stacktrace and the full source file (so the reported error location can be correlated to the source).

Would you mind providing a bit more information here? 🙇

**Comment by Jorgeee1** [comment]
Thank you for your answer and sorry for the initial lack of information!
Here is the full error stacktrace:

 ```
meteor://💻app/app/app.js:44
                        callback(null, newdata);
                         
 TypeError: callback is not a function
     at Request.userCallback (server/main.js:46:19)
     at Request._this.callback (C:\Users\Jorge\meteor\app\node_modules\tedious\lib\request.js:48:27)
     at Connection.endOfMessageMarkerReceived (C:\Users\Jorge\meteor\app\node_modules\tedious\lib\connection.js:1689:27)
     at Connection.dispatchEvent (C:\Users\Jorge\meteor\app\node_modules\tedious\lib\connection.js:857:45)
     at Parser.<anonymous> (C:\Users\Jorge\meteor\app\node_modules\tedious\lib\connection.js:683:18)
     at emitOne (events.js:116:13)
     at Parser.emit (events.js:211:7)
     at Parser.<anonymous> (C:\Users\Jorge\meteor\app\node_modules\tedious\lib\token\token-stream-parser.js:54:15)
     at emitOne (events.js:116:13)
     at Parser.emit (events.js:211:7)
```
I am using Meteor but I don't think it is a significant fact. Apart from what I've posted before, there is no more code except from strings defining connection and config, which are not related to the problem.

Thank you very much!

**Comment by tvrprasad** [comment]
> 'xxx' : function(data, callback){

Is it possible that "callback" being passed here is not a function?

**Comment by arthurschreiber** [comment]
I think @tvrprasad is right - It looks like the `callback` you're passing is not a valid function object.

**Comment by arthurschreiber** [comment]
Closing this due to inactivity. If you're still running into this issue, please let us know! 👍
