### ISSUE TITLE
TimeoutError: ResourceRequest timed out 

### ISSUE THREAD

**Issue by GeekyDeaks** [tediousjs/tedious#711]
Got an odd one that I'm looking for suggestions on how to diagnose. We have a node.js service running on an Azure Web App, which uses the following modules:

tedious version: 2.3.1 
mssql version: 4.1.0
knex version: 0.14.4

Periodically, the live deployment on Azure suffers from the following scenario:

```
2018-02-25T21:30:21.817Z knex:client acquired connection from pool: __knexUid1
2018-02-25T21:30:21.817Z knex:query select [id] from [variable] where [session_id] = @p0 and [name] = @p1
2018-02-25T21:30:21.834Z knex:bindings [ 27, 'stage.t1.count' ]
Sun, 25 Feb 2018 21:30:21 GMT mssql:tedious req: query: select [id] from [variable] where [session_id] = @p0 and [name] = @p1
Sun, 25 Feb 2018 21:30:21 GMT mssql:tedious req: query ok
2018-02-25T21:30:21.896Z knex:client releasing connection to pool: __knexUid1
2018-02-25T21:30:21.911Z knex:client acquired connection from pool: __knexUid2
2018-02-25T21:30:21.911Z knex:query update [variable] set [value] = @p0, [type] = @p1 where [session_id] = @p2 and [name] = @p3 and [index] = @p4;select @@rowcount
2018-02-25T21:30:21.927Z knex:bindings [ '2063', 'number', 27, 'stage.t1.count', 0 ]
Sun, 25 Feb 2018 21:30:21 GMT mssql:tedious req: query: update [variable] set [value] = @p0, [type] = @p1 where [session_id] = @p2 and [name] = @p3 and [index] = @p4;select @@rowcount
Sun, 25 Feb 2018 21:30:21 GMT mssql:tedious req: query ok
2018-02-25T21:30:21.958Z knex:client releasing connection to pool: __knexUid2
2018-02-25T21:30:22.854Z knex:client acquired connection from pool: __knexUid1
2018-02-25T21:30:22.854Z knex:query select [value], [type] from [variable] where [session_id] = @p0 and [name] = @p1 order by [index] asc
2018-02-25T21:30:22.870Z knex:bindings [ 27, 'survey.active' ]
Sun, 25 Feb 2018 21:30:22 GMT mssql:tedious req: query: select [value], [type] from [variable] where [session_id] = @p0 and [name] = @p1 order by [index] asc
Sun, 25 Feb 2018 21:30:22 GMT mssql:tedious req: query ok
2018-02-25T21:30:22.886Z knex:client releasing connection to pool: __knexUid1
2018-02-25T21:30:22.917Z knex:client acquired connection from pool: __knexUid2
2018-02-25T21:30:22.917Z knex:query select [value], [type] from [variable] where [session_id] = @p0 and [name] = @p1 order by [index] asc
2018-02-25T21:30:22.917Z knex:bindings [ 27, 'survey.stage' ]
Sun, 25 Feb 2018 21:30:22 GMT mssql:tedious req: query: select [value], [type] from [variable] where [session_id] = @p0 and [name] = @p1 order by [index] asc
2018-02-25T21:30:37.947Z knex:client releasing connection to pool: __knexUid2
2018-02-25T21:30:37.962Z - error: fb/sid.27 Idle.timeout() TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (D:\home\site\wwwroot\node_modules\generic-pool\lib\ResourceRequest.js:62:17)
    at Timeout.bound (D:\home\site\wwwroot\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```

I captured the above on our staging environment, with only one instance of the background process running and all the SQL serialised to aid debugging.

From the above, it looks like a simple case of the DB timing out after 15 seconds, but when I interrogate the DB, it says the longest running query was 110ms, so something is not telling the truth.

After the first timeout, the pool connection that throws the error never works again, causing the application to become unstable.  As a workaround, we are simply letting it crash.

I have tried to replicate this on our dev environments, which are run locally on laptops (OSX) and have been unable to get it to fail.  I can get the staging environment to fall over within about 30 minutes, but I have run a dev instance for over 24 hours with the same config/code/DB and it's not suffered a single hiccup.

Diagnosing this on Azure is a royal PITA.  So I am posting this in the hope that someone has some bright ideas on how to nail this one 😃

**Comment by GeekyDeaks** [comment]
This appears to have been fixed with https://github.com/tgriesser/knex/pull/2450 - so it actually seems to be a pool issue.

**Comment by AnishGandhi15992** [comment]
Any solution to this issue, This error is occurring every 3-4 days. I am losing my business due to this.

**Comment by v-suhame** [comment]
@AnishGandhi15992 If you are using an ORM or connection pool, can you confirm if it uses latest version of tedious driver? In certain cases, while tedious is waiting for Azure's response, the pool's internal timeout gets triggered and results in this error, can you verify if that's the case? That will help in finding the package where error originates.

**Comment by catcher-in-the-try** [comment]
Please reopen this issue - this is happening not just for me but apparently for many people.

**Comment by v-suhame** [comment]
@catcher-in-the-try We have #598 open to track `Request timeout`. Can you share a repo that uses tedious directly to produce this issue?

**Comment by settinghead** [comment]
This is happening to me as well. Azure + MSSQL + `mssql` package.

**Comment by AnishGandhi15992** [comment]
@v-suhame we are using connection pool and yes tedious version is latest

**Comment by v-suhame** [comment]
@settinghead @AnishGandhi15992 As mentioned in the prior comments, can you guys confirm that error is not due to the connection pool's internal timeout being triggered while tedious is waiting for SQL Server's response?
Also, can you share the repo using tedious?
