### ISSUE TITLE
Unhandled ETIMEDOUT error on connection timeout

### ISSUE THREAD

**Issue by kuseni** [tediousjs/tedious#782]
Node.js 8.11.4
tedious@2.6.4
Windows 10 Pro 1803 17134.191

Code:
```javascript
log('started');

var conn = new Connection({
	server:   '8.8.8.8',
	userName: 'test',
	password: 'test' });

conn.on('connect', function(err) {
	log(`connect(): err="${err}"`);
	if(err)
		return;
	conn.close();
});

conn.on('end',   ()    => { log('end()'); });
conn.on('debug', (msg) => { log(`debug(): ${msg}`); });
//conn.on('error', (err) => { log(`error(): err="${err}"`); });
```

Log:
```
2018-08-16 23:41:15.941: started
2018-08-16 23:41:30.954: debug(): Failed to connect to 8.8.8.8:1433 in 15000ms
2018-08-16 23:41:30.959: connect(): err="ConnectionError: Failed to connect to 8.8.8.8:1433 in 15000ms"
2018-08-16 23:41:30.976: debug(): State change: Connecting -> Final
2018-08-16 23:41:30.980: end()
2018-08-16 23:41:36.956: debug(): Connection lost - connect ETIMEDOUT 8.8.8.8:1433

events.js:183
      throw er; // Unhandled 'error' event
      ^
ConnectionError: Connection lost - connect ETIMEDOUT 8.8.8.8:1433
    at ConnectionError (***\node_modules\tedious\lib\errors.js:12:12)
    at Connection.socketError (***\node_modules\tedious\lib\connection.js:1020:28)
    at ***\node_modules\tedious\lib\connection.js:861:25
    at Socket.onError (***\node_modules\tedious\lib\connector.js:49:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I expect not receiving unhandled error and closing app immediatly after connect event (not 6 seconds later).

**Comment by Suraiya-Hameed** [comment]
#659 should have fixed this 🤔 looks like something is amiss as your are already in the latest driver, @Hadis-Fard should be able to have a look at it once she is back from vacation.

**Comment by Hadis-Fard** [comment]
@kuseni I'm not able to reproduce the issue, looking at the code in https://github.com/tediousjs/tedious/blob/master/src/connection.js#L825, if the socket is in `FINAL` state then it wouldn't be reach to the error event, which from the log you have sent it is FINAL state 🤷‍♀️

**Comment by kuseni** [comment]
@Hadis-Fard , in my case [Connector.executeForIP](https://github.com/tediousjs/tedious/blob/08a65bf81a109204587d57f78e149d771c2075a1/src/connector.js#L19)() is invoked. First of all **Connection.connectTimeout()** emit **connect** event with **err** arg and doesn't destroy socket. Then **error** event in **Connector.executeForIP()** is generated and raise unhandled error. **connect** event in **Connector.executeForIP()** is not generated, so your callback with **socket** arg is never called.

**Comment by kuseni** [comment]
... I think, **connectTimeout()** should destroy socket before socket's **error** event

**Comment by Hadis-Fard** [comment]
@kuseni it works as expected in both ip and host name. Could you post the complete code and the result of `npm show tedious version` ?

**Comment by kuseni** [comment]
```
z:\>npm show tedious version
2.6.4
```
```javascript
const util = require('util');
const Connection = require('tedious').Connection;

function log(...args) {
	var dt = new Date();
	dt.setMinutes(dt.getMinutes() - dt.getTimezoneOffset());
	process.stdout.write(`${dt.toISOString().slice(0, -1).replace('T', ' ')}: ${util.format.apply(null, args).replace(/\n/g, '\n  ')}\n`);
}

log('started');

var conn = new Connection({
	server:   '8.8.8.8',
	userName: 'test',
	password: 'test' });

conn.on('connect', (err) => {
	log(`connect(): err="${err}"`);
	if(err)
		return;
	conn.close();
});

conn.on('end',   ()    => { log('end()'); });
conn.on('debug', (msg) => { log(`debug(): ${msg}`); });
//conn.on('error', (err) => { log(`error(): err="${err}"`); });
```
```
2018-10-03 21:56:46.207: started
2018-10-03 21:57:01.226: debug(): Failed to connect to 8.8.8.8:1433 in 15000ms
2018-10-03 21:57:01.234: connect(): err="ConnectionError: Failed to connect to 8.8.8.8:1433 in 15000ms"
2018-10-03 21:57:01.241: debug(): State change: Connecting -> Final
2018-10-03 21:57:01.243: end()
2018-10-03 21:57:07.227: debug(): Connection lost - connect ETIMEDOUT 8.8.8.8:1433

events.js:183
      throw er; // Unhandled 'error' event
      ^
ConnectionError: Connection lost - connect ETIMEDOUT 8.8.8.8:1433
    at ConnectionError (z:\cci\ws\ma\ws\node_modules\tedious\lib\errors.js:12:12)
    at Connection.socketError (z:\cci\ws\ma\ws\node_modules\tedious\lib\connection.js:1020:28)
    at z:\cci\ws\ma\ws\node_modules\tedious\lib\connection.js:861:25
    at Socket.onError (z:\cci\ws\ma\ws\node_modules\tedious\lib\connector.js:49:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

Once more...

At 21:56:46 **new Connection(...)** is called, which creates socket in **Connector.executeForIp()**, call stack:
```
executeForIP (connector.js:41)
execute (connector.js:33)
connectOnPort (connection.js:859)
connect (connection.js:830)
initialiseConnection (connection.js:554)
enter (connection.js:1669)
transitionTo (connection.js:993)
Connection (connection.js:523)
(anonymous) (test01.js:12)
...
```
It's local socket, **Connection** doesn't know about it (so it can't destroy it on connection timeout). Local handlers of **connect** and **error** events of socket are set, but not invoked yet.

At 21:57:01 **Connection**'s **connect** event is emitted, call stack:
```
conn.on (test01.js:18)
emitOne (events.js:116)
emit (events.js:211)
connectTimeout (connection.js:936)
(anonymous) (connection.js:906)
...
``` 
**Connection.connectTimeout()** emits **connect** event, then calls **this.dispatchEvent('connectTimeout')** which calls **this.cleanupConnection()** which calls **this.closeConnection()** with code
```
if (this.socket) {
  this.socket.destroy();
}
```
But **this.socket == undefined** in this place, because local socket created in **Connector.executeForIp()** is not trasferred to **Connection** object.

Finally, at 21:57:07 local socket created in **Connector.executeForIp()** emits **error** event handled by local **onError()** which destroys socket at last and calls **cb(err)** which calls **this.socketError()** which emits unhandled **error** event.

Handler of socket's **connect** event in **Connector.executeForIp()** is never called, so local socket created there is not transferred to callback in **Connection** object.

**I expect to receive only connect event in my script with err != null and don't expect to wait 6 seconds after it and receive unhandled error.**

**Comment by communque** [comment]
Experienced the error
`"Unhandled 'error' event
ConnectionError: Connection lost - read ECONNRESET`

Node is hosting on an AWS EC2 Windows machine with MS-SQL on an AWS RDS.

Here's a more complete error report...


> events.js:167
      throw er; // Unhandled 'error' event
      ^
ConnectionError: Connection lost - read ECONNRESET
    at ConnectionError (**\node_modules\tedious\lib\errors.js:12:12)
    at Connection.socketError (**\node_modules\tedious\lib\connection.js:1028:28)
    at Socket.<anonymous> (**\node_modules\tedious\lib\connection.js:878:18)
    at Socket.emit (events.js:187:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Connection.socketError (**\node_modules\tedious\lib\connection.js:1028:14)
    at Socket.<anonymous> (**\node_modules\tedious\lib\connection.js:878:18)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
>

**Comment by IanChokS** [comment]
Hi @communque @kuseni, are you still experience these errors with the latest tedious version?

**Comment by jeffmcmahan** [comment]
I experience this issue if I take my dev machine offline to test error handling. It hangs and then the timeout kills the process no matter how I try to catch it.
