### ISSUE TITLE
Too large money value will make nodejs crash.

### ISSUE THREAD

**Issue by heroboy** [tediousjs/tedious#812]
https://github.com/tediousjs/tedious/blob/234cf6c26d3b7d06e4c1f25b7b2ef5b00ff87729/src/tracking-buffer/writable-tracking-buffer.js#L275-L277

**Comment by spanditcaa** [comment]
curious, what version of node ?

**Comment by heroboy** [comment]
@spanditcaa any version . Because `Math.floor(value * SHIFT_RIGHT_32)` overflow.

**Comment by heroboy** [comment]
try this:
```
function TestMoney()
{
	db.acquire((err,conn)=>{
		let request = new tedious.Request('select 1;',function(err){
			if (err)
			{
				console.log(err);
				return;
			}
		});
		request.addParameter('v',tedious.TYPES.Money,1e99);
		conn.execSql(request);
	})
}
```
output:
```
PS D:\projects\GameWebApi> node test
internal/buffer.js:35
    throw new ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -2147483648 and <= 2147483647. Received 2.3283064365386963e+93
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32LE (internal/buffer.js:515:3)
    at Buffer.writeInt32LE (internal/buffer.js:684:10)
    at WritableTrackingBuffer.writeInt32LE (D:\projects\GameWebApi\node_modules\tedious-connection-pool\node_modules\tedious\lib\tracking-buffer\writable-tracking-buffer.js:179:19)
    at WritableTrackingBuffer.writeMoney (D:\projects\GameWebApi\node_modules\tedious-connection-pool\node_modules\tedious\lib\tracking-buffer\writable-tracking-buffer.js:302:12)
    at Object.writeParameterData (D:\projects\GameWebApi\node_modules\tedious\lib\data-types\money.js:22:14)
    at new RpcRequestPayload (D:\projects\GameWebApi\node_modules\tedious-connection-pool\node_modules\tedious\lib\rpcrequest-payload.js:95:12)
    at Connection.execSql (D:\projects\GameWebApi\node_modules\tedious-connection-pool\node_modules\tedious\lib\connection.js:883:58)
    at Object.TestMoney.db.acquire [as callback] (D:\projects\GameWebApi\test.js:76:8)
    at ConnectionPool.setUsed (D:\projects\GameWebApi\node_modules\tedious-connection-pool\lib\connection-pool.js:216:12)
```

**Comment by heroboy** [comment]
If the type is `Int`, it won't crash. Even `1e99` is out of the range of `Int`. So I think it may not throw exception when the type is `money`.

**Comment by heroboy** [comment]
If the type is `Int`,and the value is `1e9999`(Infinity). It will call the callback with `RequestError: Validation failed for parameter 'v'. Invalid number.`

**Comment by heroboy** [comment]
@Hadis-Fard ok, I will try it next week.

**Comment by roschreiber** [comment]
This was fixed in `tedious@16.7.0` with commit 19cb0735.
