### ISSUE TITLE
data-type test failed.

### ISSUE THREAD

**Issue by heroboy** [tediousjs/tedious#816]
```
data-type: .FFFF.
AssertionError: 42172 === 42171
    at Object.strictEqual (D:\projects\tedious\node_modules\nodeunit\lib\types.js:83:39)
    at Object.strictEqual (D:\projects\tedious\test\unit/data-type.js:49:10)
    at Object.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16
    at Object.exports.runTest (D:\projects\tedious\node_modules\nodeunit\lib\core.js:70:9)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:118:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:513:13
    at iterate (D:\projects\tedious\node_modules\nodeunit\deps\async.js:123:13)
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:134:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:518:13
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:131:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at Immediate.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\types.js:146:17)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)

AssertionError: 42173 === 42172
    at Object.strictEqual (D:\projects\tedious\node_modules\nodeunit\lib\types.js:83:39)
    at Object.strictEqual (D:\projects\tedious\test\unit/data-type.js:49:10)
    at Object.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16
    at Object.exports.runTest (D:\projects\tedious\node_modules\nodeunit\lib\core.js:70:9)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:118:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:513:13
    at iterate (D:\projects\tedious\node_modules\nodeunit\deps\async.js:123:13)
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:134:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:518:13
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:131:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at Immediate.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\types.js:146:17)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)

AssertionError: 42172 === 42171
    at Object.strictEqual (D:\projects\tedious\node_modules\nodeunit\lib\types.js:83:39)
    at Object.strictEqual (D:\projects\tedious\test\unit/data-type.js:66:10)
    at Object.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16
    at Object.exports.runTest (D:\projects\tedious\node_modules\nodeunit\lib\core.js:70:9)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:118:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:513:13
    at iterate (D:\projects\tedious\node_modules\nodeunit\deps\async.js:123:13)
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:134:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at Immediate.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\types.js:146:17)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)

AssertionError: 42173 === 42172
    at Object.strictEqual (D:\projects\tedious\node_modules\nodeunit\lib\types.js:83:39)
    at Object.strictEqual (D:\projects\tedious\test\unit/data-type.js:66:10)
    at Object.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16
    at Object.exports.runTest (D:\projects\tedious\node_modules\nodeunit\lib\core.js:70:9)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:118:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:513:13
    at iterate (D:\projects\tedious\node_modules\nodeunit\deps\async.js:123:13)
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:134:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at Immediate.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\types.js:146:17)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)

AssertionError: <Buffer 06 7f 51 01 17 3a 0b> deepEqual <Buffer 06 7f 51 01 16 3a 0b>
    at Object.deepEqual (D:\projects\tedious\node_modules\nodeunit\lib\types.js:83:39)
    at Object.deepEqual (D:\projects\tedious\test\unit/data-type.js:81:10)
    at Object.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16
    at Object.exports.runTest (D:\projects\tedious\node_modules\nodeunit\lib\core.js:70:9)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:118:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:513:13
    at iterate (D:\projects\tedious\node_modules\nodeunit\deps\async.js:123:13)
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:134:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at Immediate.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\types.js:146:17)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)

AssertionError: <Buffer 06 7f 51 01 18 3a 0b> deepEqual <Buffer 06 7f 51 01 17 3a 0b>
    at Object.deepEqual (D:\projects\tedious\node_modules\nodeunit\lib\types.js:83:39)
    at Object.deepEqual (D:\projects\tedious\test\unit/data-type.js:81:10)
    at Object.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16
    at Object.exports.runTest (D:\projects\tedious\node_modules\nodeunit\lib\core.js:70:9)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:118:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:513:13
    at iterate (D:\projects\tedious\node_modules\nodeunit\deps\async.js:123:13)
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:134:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at Immediate.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\types.js:146:17)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)

AssertionError: <Buffer 03 17 3a 0b> deepEqual <Buffer 03 16 3a 0b>
    at Object.deepEqual (D:\projects\tedious\node_modules\nodeunit\lib\types.js:83:39)
    at Object.deepEqual (D:\projects\tedious\test\unit/data-type.js:97:10)
    at Object.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16
    at Object.exports.runTest (D:\projects\tedious\node_modules\nodeunit\lib\core.js:70:9)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:118:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:513:13
    at iterate (D:\projects\tedious\node_modules\nodeunit\deps\async.js:123:13)
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:134:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at Immediate.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\types.js:146:17)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)

AssertionError: <Buffer 03 18 3a 0b> deepEqual <Buffer 03 17 3a 0b>
    at Object.deepEqual (D:\projects\tedious\node_modules\nodeunit\lib\types.js:83:39)
    at Object.deepEqual (D:\projects\tedious\test\unit/data-type.js:97:10)
    at Object.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:236:16
    at Object.exports.runTest (D:\projects\tedious\node_modules\nodeunit\lib\core.js:70:9)
    at D:\projects\tedious\node_modules\nodeunit\lib\core.js:118:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:513:13
    at iterate (D:\projects\tedious\node_modules\nodeunit\deps\async.js:123:13)
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:134:25
    at D:\projects\tedious\node_modules\nodeunit\deps\async.js:515:17
    at Immediate.<anonymous> (D:\projects\tedious\node_modules\nodeunit\lib\types.js:146:17)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by heroboy** [comment]
maybe https://github.com/tediousjs/tedious/issues/767
