### ISSUE TITLE
Prepared Statement: TypeError: parameter.type.validate is not a function with sql.Geometry

### ISSUE THREAD

**Issue by markddrake** [tediousjs/tedious#817]
The following code 

```
"use strict"
const sql = require('mssql');

   const connectionDetails = {
      server    : "192.168.1.250"
     ,user      : "sa"
     ,database  : "clone"
     ,password  : "oracle"
	 ,options: {
        encrypt: false // Use this if you're on Windows Azure

      }
    }
  
async function main() {  

  let conn
  let results
  try {
    
    conn = new sql.ConnectionPool(connectionDetails);
	await conn.connect()
	await conn.query(`SET QUOTED_IDENTIFIER ON`);
    
    const statement = `if object_id('"dbo"."T1"','U') is NULL create table "dbo"."T1" ("location" geometry);`
    const results = await conn.query(statement);
    
    const ps = new sql.PreparedStatement(conn);
    ps.input('P1',sql.Geometry);
    ps.prepare(`insert into "dbo"."T1" ("location") values (@P1)`);
    resuls = await ps.execute({P1:null});
  } catch (e) {
    console.log('Failed');
    console.log(e);
  }
  
  conn.close();
}

main();
```
Results in

```
C:\Development\YADAMU\MSSQL\node\node_modules\tedious\lib\request.js:191
        var _value = parameter.type.validate(parameter.value);
                                    ^

TypeError: parameter.type.validate is not a function
    at Request.validateParameters (C:\Development\YADAMU\MSSQL\node\node_modules\tedious\lib\request.js:191:37)
    at Connection.callProcedure (C:\Development\YADAMU\MSSQL\node\node_modules\tedious\lib\connection.js:1427:15)
    at Immediate.parent.acquire (C:\Development\YADAMU\MSSQL\node\node_modules\mssql\lib\tedious.js:1060:20)
    at runCallback (timers.js:697:11)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

C:\Development\YADAMU\MSSQL>
```
Admitted newbie to MSQL so apologies in advance if I'm being stupid.

**Comment by markddrake** [comment]
Also note the error is not 'caught' by the try/catch block..

**Comment by markddrake** [comment]
The same behavior is observed with a Geography column

**Comment by Suraiya-Hameed** [comment]
Hey @markddrake, `tedious` doesn't support geometry or geography type, for supported types refer http://tediousjs.github.io/tedious/api-datatypes.html. `mssql` is likely doing some internal mapping or conversion to support it, they should be able to help you if you raise this issue in there [repository](https://github.com/tediousjs/node-mssql/issues).

**Comment by markddrake** [comment]
ReFiled in correct repository https://github.com/tediousjs/node-mssql/issues/743

Sorry Guys...
