### ISSUE TITLE
getaddrinfo ENOTFOUND  Error 

### ISSUE THREAD

**Issue by instantwpuserwin** [tediousjs/tedious#831]
Hey all;

Trying to connect to my ms sql db in winhost.
But I am getting error. 

Details below. Would appreciate any help. Thanks a lot.

FYI: This works via SQL Server management studio 2014. I used same config as mentioned below.

```
 var config = {
        user: 'xxxxx_userid',
        password: 'xxxxxxxx',
        server: 'tcp:s08.winhost.com', 
        database: 'DB_xxxxx' 
    };
```

```	
	{ ConnectionError: Failed to connect to tcp:s08.winhost.com:1433 - getaddrinfo ENOTFOUND tcp:s08.winhost.com
    at Connection.tedious.once.err (C:\Users\mydevlappie\Desktop\notes-node\node_modules\mssql\lib\tedious.js:239:17)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Connection.socketError (C:\Users\mydevlappie\Desktop\notes-node\node_modules\tedious\lib\connection.js:1008:12)
    at Connector.execute (C:\Users\mydevlappie\Desktop\notes-node\node_modules\tedious\lib\connection.js:874:21)
    at GetAddrInfoReqWrap.dns.lookup [as callback] (C:\Users\mydevlappie\Desktop\notes-node\node_modules\tedious\lib\connector.js:48:16)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:69:17)
  code: 'ESOCKET',
  originalError:
   { ConnectionError: Failed to connect to tcp:s08.winhost.com:1433 - getaddrinfo ENOTFOUND tcp:s08.winhost.com
       at ConnectionError (C:\Users\mydevlappie\Desktop\notes-node\node_modules\tedious\lib\errors.js:13:12)
       at Connection.socketError (C:\Users\mydevlappie\Desktop\notes-node\node_modules\tedious\lib\connection.js:1008:28)
       at Connector.execute (C:\Users\mydevlappie\Desktop\notes-node\node_modules\tedious\lib\connection.js:874:21)
       at GetAddrInfoReqWrap.dns.lookup [as callback] (C:\Users\mydevlappie\Desktop\notes-node\node_modules\tedious\lib\connector.js:48:16)
       at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:69:17)
     message:
      'Failed to connect to tcp:s08.winhost.com:1433 - getaddrinfo ENOTFOUND tcp:s08.winhost.com',
     code: 'ESOCKET' },
  name: 'ConnectionError' }
{ ConnectionError: Connection is closed.
    at Request._query (C:\Users\mydevlappie\Desktop\notes-node\node_modules\mssql\lib\base.js:1344:37)
    at Request._query (C:\Users\mydevlappie\Desktop\notes-node\node_modules\mssql\lib\tedious.js:531:11)
    at Request.query (C:\Users\mydevlappie\Desktop\notes-node\node_modules\mssql\lib\base.js:1280:12)
    at C:\Users\mydevlappie\Desktop\notes-node\Server.js:29:17
    at _poolCreate.then.catch.err (C:\Users\mydevlappie\Desktop\notes-node\node_modules\mssql\lib\base.js:276:7) code: 'ECONNCLOSED', name: 'ConnectionError' }
```

**Comment by Hadis-Fard** [comment]
Are you able to connect to the server with the SSMS? 🤔

**Comment by arthurschreiber** [comment]
You don't need to prefix the server name with `tcp:`. Try this instead:

```
   server: 's08.winhost.com',
```

**Comment by NathanBarsoti8** [comment]
created a container with the instance of Mssql
when I go to SSMS I can connect
![image](https://user-images.githubusercontent.com/38732047/88043656-221fec00-cb24-11ea-84b4-0be17ba669a8.png)

butttt, when I try connect I got this error
![image](https://user-images.githubusercontent.com/38732047/88044411-7034ef80-cb24-11ea-8488-d5aa21505031.png)

Here is my config
![image](https://user-images.githubusercontent.com/38732047/88044277-64492d80-cb24-11ea-85e3-4dd9eccf82e8.png)
