### ISSUE TITLE
Error Connecting with sql 2000 "CryptoApi"

### ISSUE THREAD

**Issue by YnievesDotNet** [tediousjs/tedious#840]
I have this error when I try connect to sql2000 server

`
Tedious-Connection-Pool: filling pool with 1
Tedious-Connection-Pool: creating connection: 1
Tedious-Connection-Pool: connection connected: 1
Tedious-Connection-Pool: connection closing because of error
{ ConnectionError: CryptoAPI function 'CryptAcquireContext' failed. Error 0x8009001d: (Error description unavailable).
    at ConnectionError (/Users/ynievesdotnet/Projects/userExtractor/node_modules/tedious-connection-pool/node_modules/tedious/lib/errors.js:12:12)
    at Parser.<anonymous> (/Users/ynievesdotnet/Projects/userExtractor/node_modules/tedious-connection-pool/node_modules/tedious/lib/connection.js:358:38)
    at Parser.emit (events.js:182:13)
    at Parser.<anonymous> (/Users/ynievesdotnet/Projects/userExtractor/node_modules/tedious-connection-pool/node_modules/tedious/lib/token/token-stream-parser.js:54:15)
    at Parser.emit (events.js:182:13)
    at addChunk (/Users/ynievesdotnet/Projects/userExtractor/node_modules/tedious-connection-pool/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Users/ynievesdotnet/Projects/userExtractor/node_modules/tedious-connection-pool/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Parser.Readable.push (/Users/ynievesdotnet/Projects/userExtractor/node_modules/tedious-connection-pool/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at Parser.Transform.push (/Users/ynievesdotnet/Projects/userExtractor/node_modules/tedious-connection-pool/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at doneParsing (/Users/ynievesdotnet/Projects/userExtractor/node_modules/tedious-connection-pool/node_modules/tedious/lib/token/stream-parser.js:102:18)
  message:
   "CryptoAPI function 'CryptAcquireContext' failed. Error 0x8009001d: (Error description unavailable).",
  code: 'ELOGIN' }
`
How I fix that.

Best Regards, Yoinier

**Comment by arthurschreiber** [comment]
Which version of tedious are you using? Newer versions of tedious contain a fix for encryption related issues in combination with older SQL Server  / Windows versions.

**Comment by YnievesDotNet** [comment]
ins this moment I are using 
`
    "tedious": "^3.0.1",
    "tedious-connection-pool": "^1.0.5"
`

**Comment by arthurschreiber** [comment]
I think this was fixed in `v4.0.3`. If you can't upgrade to that version, you could try applying the changes from the following commit and see if that fixes the issue: https://github.com/tediousjs/tedious/commit/7b04e1c

**Comment by IanChokS** [comment]
@YnievesDotNet if upgrading to the latest Tedious version does not resolve your issue, feel free to re-open this issue.
