### ISSUE TITLE
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by Alextunchii** [tediousjs/tedious#853]
Hi! Encountered this issue and haven't found any related info about it...

I started getting this error:
```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:52:11)
    at Buffer.readUInt8 (internal/buffer.js:144:5)
    at Packet.type (node_modules/tedious/lib/packet.js:144:26)
    at IncomingMessageStream.processBufferedData (node_modules/tedious/lib/incoming-message-stream.js:76:50)
    at IncomingMessageStream._transform (node_modules/tedious/lib/incoming-message-stream.js:113:12)
    at IncomingMessageStream.Transform._read (node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at IncomingMessageStream.Transform._write (node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at IncomingMessageStream.Writable.write (node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:666:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
```
when have rewritten config from just an object:
```
let config = {
    user: process.env.DB_USER_NAME,
    password: process.env.DB_USER_NAME,
    server: process.env.DB_HOST,
    port: +process.env.DB_PORT, //required numeric value to pass
    database: process.env.DB_NAME,
    requestTimeout: 70000,
    connectionTimeout: 75000,
    parseJSON: true,
    options: {
        encrypt: false,
    },
};
```

to class:
```
module.exports = class BaseConfig {

    constructor(datebase) {
    this.user = 'wrapppy';
    this.password = 'blabla';
    this.server = 'amazonaws.com';
    this.port = 3306; //required numeric value to pass
    this.database = datebase;
    this.requestTimeout = 120000;
    this.connectionTimeout = 120000;
    this.parseJSON = true;
    this.options = {
        encrypt: false
    };

    }

    getConfig() {
        return {
            user: this.user,
            password: this.password,
            server: this.server,
            port: parseInt(this.port), //required numeric value to pass
            database: this.database,
            requestTimeout: this.requestTimeout,
            connectionTimeout: this.connectionTimeout,
            parseJSON: this.parseJSON,
            options: this.options
        }
    }
};
```

In a file where import this class:
const BaseConfig = require('../../database/databaseConfig');
const baseConfigObject = new BaseConfig('bal_dev');

it.only('should ', async function () {
        console.log(baseConfigObject.getConfig());
        let connection = await sql.connect(baseConfigObject.getConfig());
        csdbResponse = await queryToDatabase('select count(*) from users;');
        console.log(csdbResponse)
    });

in console.log(baseConfigObject.getConfig()); i have everything correct:
```
{ user: 'bowl',
  password: 'wg1-trreeaaee',
  server:
   'east-1.rds.amazonaws.com',
  port: 3306,
  database: 'bal_dev',
  requestTimeout: 120000,
  connectionTimeout: 120000,
  parseJSON: true,
  options: { encrypt: false } }
```

**Comment by chdh** [comment]
@Alextunchii  You are connecting to a MySQL server (port 3306), not to a MS-SQL server.

@arthurschreiber There is a programming error in `incoming-message-stream.js`. In `processBufferedData()` the `length` variable is never checked to be `>= HEADER_LENGTH`. If the first 2 bytes received are 0, the `data` buffer passed to the `Packet()` constructor is empty and this leads to a `ERR_BUFFER_OUT_OF_BOUNDS` in `Packet.type()`.

**Comment by Alextunchii** [comment]
@chdh 
Yeah, I see... I mixed up configs. Sorry for distracting you and thank you for your prompt which resolved consequences of my evening unattentiveness...
