### ISSUE TITLE
Invalid usage of the option NEXT in the FETCH statement.

### ISSUE THREAD

**Issue by MichaelJCole** [tediousjs/tedious#872]
Hi there, I'm just starting to use Tedious through the feathers-sequelize package.  

I'm getting an [error that seems related to SQL Server versions](https://stackoverflow.com/questions/30632779/tedious-or-sequelize-uses-the-wrong-syntax-for-findone/54837260#54837260).

SQL Server is a new animal for me.  Anything obvious I'm missing?  

Thank you!

I'm working with this version of mssql:
```
Microsoft SQL Server 2014 - 12.0.2000.8 (X64) 
	Feb 20 2014 20:04:26 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows NT 6.3 <X64> (Build 17134: ) 
```

It looks like the app starts and talks with the database.  When I use a bad password, I get an appropriate error.  Here's a good startup.  I'm connecting to an existing database schema, so these create tables shouldn't have an effect:
```
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/`
info: Feathers application started on http://localhost:3030
Executing (default): IF OBJECT_ID('[MattInf]', 'U') IS NULL CREATE TABLE [MattInf] ([MatterID] BIGINT NOT NULL , [ClientInfoClientID] BIGINT NULL, [MatterInfoRespLwyr] BIGINT NULL, [MatterInfoDefRateAmt] FLOAT NULL, [MatterInfoFileDesc] NVARCHAR(900) NULL, [MatterInfoMatterNum] NVARCHAR(25) NULL, [MatterInfoOpenDate] BIGINT NULL, [MatterInfoSortName] NVARCHAR(70) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([MatterID]));
Executing (default): EXEC sys.sp_helpindex @objname = N'[MattInf]';
Executing (default): IF OBJECT_ID('[ClntInfV5]', 'U') IS NULL CREATE TABLE [ClntInfV5] ([ClientInfoClientID] BIGINT NOT NULL , [ClientInfoSortName] NVARCHAR(40) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([ClientInfoClientID]));
Executing (default): EXEC sys.sp_helpindex @objname = N'[ClntInfV5]';
Executing (default): IF OBJECT_ID('[LawInf]', 'U') IS NULL CREATE TABLE [LawInf] ([LawyerID] BIGINT NOT NULL , [LawInfDeptID] BIGINT NULL, [LawInfInitials] NVARCHAR(10) NULL, [LawInfLawyerName] NVARCHAR(3000) NULL, [LawInfNickName] NVARCHAR(20) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([LawyerID]));
Executing (default): EXEC sys.sp_helpindex @objname = N'[LawInf]';
```
Here's the connection code:

```
const url = require('url');
const Sequelize = require('sequelize');

module.exports = function (app) {
  const connectionString = app.get('mssql');
  const connection = url.parse(connectionString);
  const database = connection.path.substring(1, connection.path.length);
  const { port, hostname } = connection;
  const [ username, password ] = (connection.auth || ':').split(':');
  const sequelize = new Sequelize(database, username, password, {
    dialect: 'mssql',
    host: hostname,
    logging: app.get('debug_mssql') ? console.log : false,  // customized logging
    operatorsAliases: false,
    define: {
      freezeTableName: true
    },
    dialectOptions: {
      port: parseInt(port),           // added parseInt()
      encrypt: false,
      //instanceName: 'wont_work_with_port'
    }
  });
```

Here is the model I'm using w/ sequelize:
```
// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const Lawyers = sequelizeClient.define('Lawyers', {
    // Primary Key
    LawyerID: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      allowNull: false
    },
    // Foreign Keys
    // Fields
    LawInfDeptID: {
      type: DataTypes.BIGINT,
      allowNull: true,
    },
    LawInfInitials: {
      type: DataTypes.STRING(10),
      allowNull: true,
    },
    LawInfLawyerName: {
      type: DataTypes.STRING(3000),
      allowNull: true,
    },
    LawInfNickName: {
      type: DataTypes.STRING(20),
      allowNull: true,
    },
  }, {
    tableName: 'LawInf',
    hooks: {
      beforeCount(options) {
        options.raw = true;
      },
    },
  });

  // eslint-disable-next-line no-unused-vars
  Lawyers.associate = function (models) {
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
  };

  return Lawyers;
};

```
When I try to access a LawInf, I get this error:

```
Executing (default): SELECT count(DISTINCT([Lawyers].[LawyerID])) AS [count] FROM [LawInf] AS [Lawyers];
Executing (default): SELECT [LawyerID], [LawInfDeptID], [LawInfInitials], [LawInfLawyerName], [LawInfNickName], [createdAt], [updatedAt] FROM [LawInf] AS [Lawyers] OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;
error: NotFound: Invalid usage of the option NEXT in the FETCH statement.
    at new NotFound (/home/michael/scm/project/app/sync/node_modules/@feathersjs/errors/lib/index.js:114:17)
    at exports.errorHandler.error (/home/michael/scm/project/app/sync/node_modules/feathers-sequelize/lib/utils.js:28:20)
    at tryCatcher (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by MichaelJCole** [comment]
Here is the code that's generating the query:

https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query-generator.js#L860

```
  addLimitAndOffset(options, model) {
    // Skip handling of limit and offset as postfixes for older SQL Server versions
    if (semver.valid(this.sequelize.options.databaseVersion) && semver.lt(this.sequelize.options.databaseVersion, '11.0.0')) {
      return '';
    }

    let fragment = '';
    const offset = options.offset || 0,
      isSubQuery = options.hasIncludeWhere || options.hasIncludeRequired || options.hasMultiAssociation;

    let orders = {};
    if (options.order) {
      orders = this.getQueryOrders(options, model, isSubQuery);
    }

    if (options.limit || options.offset) {
      if (!options.order || options.include && !orders.subQueryOrder.length) {
        fragment += options.order && !isSubQuery ? ', ' : ' ORDER BY ';
        fragment += this.quoteTable(options.tableAs || model.name) + '.' + this.quoteIdentifier(model.primaryKeyField);
      }

      if (options.offset || options.limit) {
        fragment += ' OFFSET ' + this.escape(offset) + ' ROWS';
      }

      if (options.limit) {
        fragment += ' FETCH NEXT ' + this.escape(options.limit) + ' ROWS ONLY';
      }
    }

    return fragment;
  },
```

**Comment by davepreston** [comment]
@MichaelJCole do you have a reason to believe this is an issue with tedious? the SQL code that is being sent to tedious does not look like valid SQL code. Specifically there is an OFFSET and FETCH with no ORDER BY clause. 
details on OFFSET/FETCH here: https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-2017#using-offset-and-fetch-to-limit-the-rows-returned

I found this issue while using feathers-sequelize (I got a similar error). I see that you've also opened an issue on sequelize regarding this same issue. I'm not a maintainer, but I'd expect they'd appreciate you closing this issue on tedious since it appears to be an issue with the generated SQL code being sent by sequelize (feathers-sequelize?) not inside tedious.

**Comment by MichaelJCole** [comment]
Hi @davepreston looks like I opened this and https://github.com/sequelize/sequelize/issues/10472, but forgot to close this one.  I think you're right.

**Comment by donvie** [comment]
https://github.com/realdubb/sequelize/commit/0c4674013486be36e96e1c310a91aaa95bd931de
this will fixed all your problem
