### ISSUE TITLE
MSI invalid state - Requests can only be made in the LoggedIn state, not the SentLogin7Withfedauth state

### ISSUE THREAD

**Issue by lenisha** [tediousjs/tedious#885]
When testing connection to Azure SQL with MSI token with code described here: https://github.com/lenisha/node-msi 

Getting error:
Requests can only be made in the LoggedIn state, not the SentLogin7Withfedauth state

request database connection debugtext: State change: Connecting -> SentPrelogin
request database connection debugtext: State change: SentPrelogin -> SentTLSSSLNegotiation
request database connection debugtext: TLS negotiated (ECDHE-RSA-AES256-GCM-SHA384, TLSv1/SSLv3)
request database connection debugtext: State change: SentTLSSSLNegotiation -> SentLogin7Withfedauth
request database connection debugtext: State change: SentLogin7Withfedauth -> ReRouting
request database connection debugtext: Packet size changed from 4096 to 4096
request database connection debugtext: connection to .database.windows.net:1433 closed
request database connection debugtext: Rerouting to c3067b8d85c8.tr26.eastus1-a.worker.database.windows.net:11090
request database connection debugtext: State change: ReRouting -> Connecting
request database connection debugtext: connected to .database.windows.net:1433
request database connection debugtext: State change: Connecting -> SentPrelogin

request database connection debugtext: State change: SentPrelogin -> SentTLSSSLNegotiation
request database connection debugtext: TLS negotiated (ECDHE-RSA-AES256-GCM-SHA384, TLSv1/SSLv3)
request database connection debugtext: State change: SentTLSSSLNegotiation -> SentLogin7Withfedauth

>>> Got connection azure sql server via tedious in request, next go to execute sql query statement 

request database connection debugtext: Requests can only be made in the LoggedIn state, not the SentLogin7Withfedauth state

Error performing select: 

{ RequestError: Requests can only be made in the LoggedIn state, not the SentLogin7Withfedauth state

    at RequestError (D:\home\site\wwwroot\node_modules\tedious\lib\errors.js:32:12)

    at Connection.makeRequest (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:1678:24)

    at Connection.execSql (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:1457:10)

    at executeStatement (D:\home\site\wwwroot\index.js:95:14)

    at Connection.<anonymous> (D:\home\site\wwwroot\index.js:59:9)

    at Connection.emit (events.js:182:13)

    at context.acquireTokenWithUsernamePassword (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:2056:20)

    at AuthenticationContext.acquireTokenWithUsernamePassword (D:\home\site\wwwroot\node_modules\adal-node\lib\authentication-context.js:259:5)

    at Connection.message (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:2053:19)

    at Connection.dispatchEvent (D:\home\site\wwwroot\node_modules\tedious\lib\connection.js:1172:36)

  message:

   'Requests can only be made in the LoggedIn state, not the SentLogin7Withfedauth state',

  code: 'EINVALIDSTATE' }

**Comment by MichaelSun90** [comment]
The fix has been merged and released.

**Comment by lenisha** [comment]
Resolved
