### ISSUE TITLE
parameter.value.getTimezoneOffset is not a function

### ISSUE THREAD

**Issue by jtara1** [tediousjs/tedious#916]
Hey, I'm working on debugging this error, but I'm using a private lib for Transact SQL / MS SQL Server that depends on tedious.

partial stacktrace 

```
            "Caused By: TypeError: parameter.value.getTimezoneOffset is not a function",
            "    at Object.writeParameterData (D:\\home\\site\\wwwroot\\node_modules\\tedious\\lib\\data-type.js:1506:39)",
            "    at new RpcRequestPayload (D:\\home\\site\\wwwroot\\node_modules\\tedious\\lib\\rpcrequest-payload.js:89:12)",
            "    at Connection.execSql (D:\\home\\site\\wwwroot\\node_modules\\tedious\\lib\\connection.js:724:58)",
```

![Snip20190625_9](https://user-images.githubusercontent.com/7478231/60141811-ddcceb80-976b-11e9-9366-a39c534d2f04.png)

I attached a debugger and inspected values above there. The data type for `param.value` does not seem what is expected for that var in that func.

We can `const moment = require('moment');` `moment.utc(1560556800000);` to see that it represents the same date that I initially used as input in our private lib for a transaction in a ms sql server db for the date `'2019-06-15'`

**Comment by jtara1** [comment]
needed the date to be of type `Date`, not string or moment
