### ISSUE TITLE
NTLM Authentication fails in NTLMResponsePayload.createResponse

### ISSUE THREAD

**Issue by FabianTe** [tediousjs/tedious#961]
Hey guys,

I am having problems using NTLM. I would like to connect to an MS SQL 2017 by using this config:

```js
const mssql = require('mssql');
const con = {
    server: 'localhost',
    database: 'mydb',
    domain:'some-vm-of-mine',
    user: 'Admin',
    options: {
        trustedConnection: true,
        instanceName: 'MYINSTANCE'
    },
    authentication: {
        type: 'ntlm',
        username: 'Admin',
        password: 'mypass',
        domain: 'some-vm-of-mine'
    }
}
await mssql.connect(con);
```

*I know that there are redundant properties, but that's what I am testing with*

When running this, I receive this error:

```
buffer.js:207
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at NTLMResponsePayload.ntHash (C:\MyProject\node_modules\tedious\lib\ntlm-payload.js:149:34)
    at NTLMResponsePayload.ntv2Hash (C:\MyProject\node_modules\tedious\lib\ntlm-payload.js:142:23)
    at NTLMResponsePayload.lmv2Response (C:\MyProject\node_modules\tedious\lib\ntlm-payload.js:130:23)
    at NTLMResponsePayload.createResponse (C:\MyProject\node_modules\tedious\lib\ntlm-payload.js:63:27)
    at new NTLMResponsePayload (C:\MyProject\node_modules\tedious\lib\ntlm-payload.js:14:22)
    at Connection.sendNTLMResponsePacket (C:\MyProject\node_modules\tedious\lib\connection.js:1229:21)
    at Connection.receivedChallenge (C:\MyProject\node_modules\tedious\lib\connection.js:1949:14)
    at Connection.dispatchEvent (C:\MyProject\node_modules\tedious\lib\connection.js:1084:36)
    at Connection.processLogin7NTLMResponse (C:\MyProject\node_modules\tedious\lib\connection.js:1408:12)
    at Connection.message (C:\MyProject\node_modules\tedious\lib\connection.js:1955:14)
    at Connection.dispatchEvent (C:\MyProject\node_modules\tedious\lib\connection.js:1084:36)
    at MessageIO.messageIo.on (C:\MyProject\node_modules\tedious\lib\connection.js:984:14)
    at MessageIO.emit (events.js:198:13)
    at MessageIO.EventEmitter.emit (domain.js:448:20)
    at Message.message.on (C:\MyProject\node_modules\tedious\lib\message-io.js:32:14)
```

Can someone tell me what I am getting wrong? Tx

**Comment by FabianTe** [comment]
Well, as usual, I figured out what the error was just a minute after creating an issue 😉 

I added a console.dir to this function inside `ntlm-payload.js` and saw that my con object was missing a password:

```js
lmv2Response(domain, user, password, serverNonce, clientNonce) {
    console.dir(arguments);
    const hash = this.ntv2Hash(domain, user, password);
    const data = Buffer.alloc(serverNonce.length + clientNonce.length, 0);
    serverNonce.copy(data);
    clientNonce.copy(data, serverNonce.length, 0, clientNonce.length);
    const newhash = this.hmacMD5(data, hash);
    const response = Buffer.alloc(newhash.length + clientNonce.length, 0);
    newhash.copy(response);
    clientNonce.copy(response, newhash.length, 0, clientNonce.length);
    return response;
}
```

**Comment by abulhasanlakhani** [comment]
Awesome man. This helped me. Thanks!
