### ISSUE TITLE
ConnectionError: Login failed for user 'myuser'

### ISSUE THREAD

**Issue by osmartinez** [tediousjs/tedious#962]
"tedious": "^6.2.0",

I am using Azure Sql Server database to connect with my web application and I get this error:

> { ConnectionError: Login failed for user 'myuser'.
    at ConnectionError (C:\Users\omartinez\Source\repos\portal\node_modules\tedious\lib\errors.js:13:12)
    at Parser.tokenStreamParser.on.token (C:\Users\omartinez\Source\repos\portal\node_modules\tedious\lib\connection.js:790:23)
    at Parser.emit (events.js:198:13)
    at Parser.parser.on.token (C:\Users\omartinez\Source\repos\portal\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
    at Parser.emit (events.js:198:13)
    at addChunk (C:\Users\omartinez\Source\repos\portal\node_modules\readable-stream\lib\_stream_readable.js:297:12)
    at readableAddChunk (C:\Users\omartinez\Source\repos\portal\node_modules\readable-stream\lib\_stream_readable.js:279:11)
    at Parser.Readable.push (C:\Users\omartinez\Source\repos\portal\node_modules\readable-stream\lib\_stream_readable.js:240:10)
    at Parser.Transform.push (C:\Users\omartinez\Source\repos\portal\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at doneParsing (C:\Users\omartinez\Source\repos\portal\node_modules\tedious\lib\token\stream-parser.js:80:14)
  message: 'Login failed for user \'myuser\'.',
  code: 'ELOGIN' }

When I try to connect to my local sql server database there is no problem, the problem comes when trying to connect to azure database.

The weird thing is that one month ago everything worked. But now I tried again with a new database and it is impossible to stablish the connection.

My config object:
`const config =
{
    authentication: {
        options: {
            userName: 'myser', // update me
            pass: 'mypassword' // update me
        },
        type: 'default'
    },
    server: 'my-server.database.windows.net',  //update me
    options:
    {
        database: 'my_db', 
        encrypt: true,
        rowCollectionOnRequestCompletion: true,
        useColumnNames: true 
    }
}`

I can connect to the database using other libraries or software (SQL Server management studio)

**Comment by IanChokS** [comment]
Hi @osmartinez , what helped you solve your problem? This way we can help others who are having the same issue as you. :smile:
